import type { QuestionEn } from "@/lib/content/types";

/** Англійський дубль додаткового пулу. */
export const questionsMoreEn: Record<string, QuestionEn> = {
  // ── dt-1: Tool definitions (extra pool) ────────────────────────────────
  "dt-1-q8": {
    prompt: "How do tool definitions affect the cost of a request?",
    choices: {
      a: "They are added to the prompt and count as input tokens on every request.",
      b: "Not at all: definitions are stored server-side after the first request.",
      c: "Only the tools the model actually called are billed.",
      d: "Only names are sent to the model, so long descriptions are free.",
    },
    whyWrong: {
      b: "The Messages API is stateless; `tools` are sent and billed with every request.",
      c: "The model sees every definition in order to choose, so all of them count as input tokens.",
      d: "The model receives full definitions with descriptions and schemas — which is exactly why descriptions affect behaviour.",
    },
    explanation:
      "Tool definitions are part of the input prompt (plus some system text for tool use). A large tool set costs more on every loop iteration, so it gets cached or trimmed.",
  },
  "dt-1-q9": {
    prompt: "What helps most?",
    scenario:
      "An internal assistant has 60 tools, but a typical request needs 2–3 of them. Input token counts are high and the model sometimes picks a similar but wrong tool.",
    choices: {
      a: "Increase `max_tokens` so the model has time to consider every tool.",
      b: "Move all tool descriptions into the system prompt and keep only names in `tools`.",
      c: "Send a separate request per tool and pick the best answer.",
      d: "Mark rarely used tools `defer_loading: true` and add the tool search tool.",
    },
    whyWrong: {
      a: "`max_tokens` caps output; it affects neither selection quality nor input size.",
      b: "Input tokens do not shrink, and descriptions get detached from schemas, which makes selection worse.",
      c: "That multiplies cost and latency, and tool selection stops being the model's decision.",
    },
    explanation:
      "Tool search lets you avoid keeping every definition in context: deferred tools are loaded on demand. A smaller visible set is both cheaper and more accurate to choose from.",
  },
  "dt-1-q10": {
    prompt: "Why validate `tool_use.input` in code if the schema is carefully written but `strict` is off?",
    choices: {
      a: "It is not needed: the API rejects any call that does not match `input_schema` before responding.",
      b: "Without `strict` the model may miss a field or get a type wrong, and its input is untrusted data.",
      c: "So the SDK can convert `input` from a JSON string to an object before calling the function.",
      d: "To reduce the number of input tokens.",
    },
    whyWrong: {
      a: "Without `strict` the API does not guarantee conformance; invalid `input` can reach your code.",
      c: "The SDK already returns `input` as a parsed object; validation is about content, not transport format.",
      d: "Validation in code has no effect on request tokens.",
    },
    explanation:
      "Tool input is generated by the model, so it is as untrusted as user input. Validate types and business rules, and on failure return a `tool_result` with `is_error: true` and a clear message.",
  },
  "dt-1-q11": {
    prompt: "Which `input_schema` elements actually help the model fill in arguments correctly?",
    choices: {
      a: "A `default` that the API fills into `input` automatically when the model omits the field.",
      b: "`enum` for fields with a finite set of values.",
      c: "A `description` on each property with the format and an example.",
      d: "A mandatory `$schema` with the spec URL, without which the tool is rejected.",
      e: "`required` for fields without which the call makes no sense.",
    },
    whyWrong: {
      a: "The API does not fill in defaults; your code handles a missing field.",
      d: "`$schema` is not required in `input_schema`; the schema is accepted without it.",
    },
    explanation:
      "A schema is a prompt too: `enum` narrows choices, property descriptions explain the format, and `required` shows what is mandatory. Defaults are applied by your code, not the API.",
  },
  "dt-1-q12": {
    prompt: "This function is passed to the Python SDK Tool Runner. Which fields end up in `required` of the generated schema?",
    choices: {
      a: "None: `@beta_tool` makes every field optional.",
      b: "`city` and `unit`, because both have type annotations.",
      c: "Only `city`.",
      d: "Only `unit`, because it has a default.",
    },
    whyWrong: {
      a: "A parameter without a default value is generated as required.",
      b: "The annotation sets the type; being required depends on having no default, and `unit` has one.",
      d: "It is the other way round: a default makes a parameter optional.",
    },
    explanation:
      "The Tool Runner builds `input_schema` from the signature: types from annotations, the description from the docstring, and required fields are parameters without a default. So the docstring effectively becomes the `description`.",
  },
  "dt-1-q13": {
    prompt: "What is the cause and what is the fix?",
    scenario:
      "A service builds the `tools` list from a plugin registry in arbitrary order and inserts the current time into the description of the `now` tool. Prompt caching is on, but `cache_read_input_tokens` is almost always 0.",
    choices: {
      a: "The `tools` prefix differs every time: sort tools deterministically and remove changing data from descriptions.",
      b: "Caching only covers `system` and `messages`; tool definitions are never cached.",
      c: "Switch models; caching is disabled for this one.",
      d: "Requests arrive too rarely and the cache expires between them — send them more often.",
    },
    whyWrong: {
      b: "`tools` is the very first part of the prefix and is cached with the rest if it is byte-for-byte stable.",
      c: "The problem is the changing prefix, not the model.",
      d: "Even an instant retry will miss if the prefix has changed.",
    },
    explanation:
      "Caching is an exact prefix match, and `tools` is rendered first. A non-deterministic order and a timestamp in a description change the prefix every time; pass the time in a message or return it from the tool itself.",
  },
  "dt-1-q14": {
    prompt: "What should you do first?",
    scenario:
      "The `book_room` tool has a `date` field of type `string`. The model sends '12 March', 'next Tuesday' or `2026-03-12` depending on how the user phrased it. The backend accepts only ISO 8601.",
    choices: {
      a: "Write a natural-language parser on the backend that understands 'next Tuesday' and similar dates.",
      b: "Change the field type to `number` and accept a Unix timestamp — it cannot be written ambiguously.",
      c: "Add a general rule to the system prompt: 'be careful with dates and formats'.",
      d: "Describe the format in the field `description` (ISO 8601, `YYYY-MM-DD`) and validate the value in code.",
    },
    whyWrong: {
      a: "That moves the model's job into fragile code and does not fix the cause — the schema never says which format is required.",
      b: "The model computes timestamps worse than it writes ISO dates; errors will increase.",
      c: "A generic request does not specify the format and is not tied to the field.",
    },
    explanation:
      "The field format is part of the contract and belongs in the field description. Validation in code catches the remaining cases and returns a specific error the model can fix.",
  },
  "dt-1-q15": {
    prompt: "A developer declared their own tool with `name: \"bash\"` and a custom `input_schema`, expecting the behaviour of Anthropic's built-in bash tool. What is wrong?",
    choices: {
      a: "Nothing: the API recognises the built-in tool by the name `bash` and swaps in its own schema.",
      b: "It is a separate user-defined tool; the built-in one is declared via `type` with no `input_schema`.",
      c: "The name `bash` is reserved for the built-in tool, so the API returns 400.",
      d: "Add `strict: true`, and the API will then treat the tool as the built-in one.",
    },
    whyWrong: {
      a: "Recognition is by the `type` field; a tool with a custom schema is an ordinary user-defined tool.",
      c: "The name is not forbidden; the problem is that you get a different tool than expected.",
      d: "`strict` only guarantees arguments match the schema and does not change the tool type.",
    },
    explanation:
      "Anthropic-defined tools (bash, text editor, memory) are declared with a `type` field and no schema — the model is trained on their format. Your code still executes them; a custom `bash` with a schema is a separate tool.",
  },
  "dt-1-q16": {
    prompt: "Which are signs of a good tool description?",
    choices: {
      a: "It says when to call the tool, not only what it does.",
      b: "It contains the full implementation code so the model understands the logic.",
      c: "It describes what is returned and what the limits are (record cap, pagination).",
      d: "It separates the tool from a similar sibling ('use the other tool to look up by email').",
      e: "It repeats the tool name in one word so as not to distract the model.",
    },
    whyWrong: {
      b: "The implementation wastes tokens; the model needs the contract — purpose, inputs, output, limits.",
      e: "A terse description forces the model to guess the purpose from the name — hence wrong calls.",
    },
    explanation:
      "The description is the main signal the model uses to choose a tool. Trigger conditions, output format, limits and the boundary with sibling tools give the biggest accuracy gains.",
  },
  // ── dt-2: The tool_use loop (extra pool) ───────────────────────────────
  "dt-2-q8": {
    prompt: "What should the code do?",
    scenario:
      "The model generates a large file via a `write_file` tool. The response came back with `stop_reason: \"max_tokens\"`, and the last block is a `tool_use` with truncated `content` in `input`.",
    choices: {
      a: "Run `write_file` with what it has and return a `tool_result` so the model writes the rest.",
      b: "Do not execute the truncated call; retry the turn with a larger `max_tokens` (large values with streaming).",
      c: "Send a user message 'Continue' so the model finishes the `input`.",
      d: "Treat it as `tool_use`, since the last block is a tool call.",
    },
    whyWrong: {
      a: "Writing a truncated file silently corrupts data; an incomplete call must not be executed.",
      c: "The model cannot append to an already emitted `tool_use` block; it will start a new turn.",
      d: "The loop must branch on `stop_reason`, and here it is `max_tokens`, meaning the response is incomplete.",
    },
    explanation:
      "Handle every `stop_reason` explicitly: `max_tokens` means truncated output even if it contains a `tool_use`. Large tool arguments need headroom in `max_tokens`.",
  },
  "dt-2-q9": {
    prompt: "Which fix is right?",
    scenario:
      "The agent loop is `while (res.stop_reason === \"tool_use\")` with no other conditions. Once the model called `search` 200 times in a row with the same query because the tool returned an empty array.",
    choices: {
      a: "Increase `temperature` so the model tries different query phrasings more often.",
      b: "Cache `search` responses so each repeated call is almost free.",
      c: "Remove `search` from the tool set.",
      d: "Add an iteration cap and a repeat detector, and make the tool explain an empty result.",
    },
    whyWrong: {
      a: "Randomness gives no progress signal and does not cap spending.",
      b: "A cheap infinite loop is still infinite.",
      c: "The agent loses a needed capability; the issue is feedback, not the tool's presence.",
    },
    explanation:
      "An iteration cap is a mandatory safeguard for any loop. The root cause of looping is a tool with no progress signal: '0 results for X; try a broader query' gives the model a way forward.",
  },
  "dt-2-q10": {
    prompt: "What goes into the `tool_use_id` of a `tool_result` block?",
    choices: {
      a: "The tool name from the `name` field of the `tool_use` block.",
      b: "The index of the block in the response `content` array.",
      c: "The `id` of the corresponding `tool_use` block (like `toolu_...`).",
      d: "The `id` of the whole message (`msg_...`).",
    },
    whyWrong: {
      a: "Several calls to one tool share a name; the link is a unique id.",
      b: "An index is not a call identifier and the API does not use it.",
      d: "One message can contain several calls; you need the id of the specific block.",
    },
    explanation:
      "Each `tool_use` block has its own `id`. The `tool_result` refers to exactly that — which is how the model matches results to calls, even when there are several.",
  },
  "dt-2-q11": {
    prompt: "A response contains two `tool_use` blocks, but the code returns a `tool_result` only for the first. What happens?",
    choices: {
      a: "The API returns a 400: every `tool_use` must get its own `tool_result` in the next message.",
      b: "The model runs the second call itself on the server and adds the result to its reply.",
      c: "The second call is silently ignored and the model continues based on the first one only.",
      d: "The model repeats the second call in its next response.",
    },
    whyWrong: {
      b: "Client tools are executed only by your code; the model has no access to them.",
      c: "An unpaired `tool_use` is a structural error in the history, not a silent case.",
      d: "There will be no next response: the request is rejected at validation.",
    },
    explanation:
      "The pairing rule: for every `tool_use`, exactly one `tool_result` with the same id in the next user message. Handle all `tool_use` blocks, not just the first one found.",
  },
  "dt-2-q12": {
    prompt: "What must a correct manual tool-use loop do on every iteration?",
    choices: {
      a: "Append the whole `res.content` to history as an assistant message.",
      b: "Keep only the model's final text to save tokens.",
      c: "Send `tools` with every request.",
      d: "Delete old `tool_result` blocks from history manually while leaving their `tool_use` blocks.",
      e: "Append the tool results as the next user message.",
    },
    whyWrong: {
      b: "Without the `tool_use` blocks the tool results have nothing to pair with, and the request fails.",
      d: "That breaks call–result pairs; context editing exists to do this consistently.",
    },
    explanation:
      "The API is stateless: every request carries `tools` and the full history, with assistant messages kept verbatim and results sent as a user message. Otherwise the model cannot see its own calls.",
  },
  "dt-2-q13": {
    prompt: "What does this code do?",
    choices: {
      a: "Uploads `get_weather` to Anthropic's servers, where the function runs in a sandbox.",
      b: "Runs the loop: calls the API, executes requested functions and returns results until the model is done.",
      c: "Makes one request and returns the first `tool_use` block without executing it.",
      d: "Starts the Claude Agent SDK with built-in filesystem tools.",
    },
    whyWrong: {
      a: "The Tool Runner executes your functions locally, in your process.",
      c: "That is plain `messages.create` behaviour; the runner executes tools and continues the loop itself.",
      d: "The Tool Runner is part of the regular SDK and works only with tools you define.",
    },
    explanation:
      "The Tool Runner is an SDK helper that automates the manual loop for your tools. Hosting, execution and tool safety stay on your side.",
  },
  "dt-2-q14": {
    prompt: "Where is the right place to implement the approval?",
    scenario:
      "A support agent has a `refund_payment` tool. The business requires a human to approve every refund, while the other tools should run automatically.",
    choices: {
      a: "Write 'always ask the user for permission before calling' in the tool description.",
      b: "Require in the system prompt that the model first warns the user about the refund.",
      c: "In code before running `refund_payment`; on rejection, a `tool_result` saying 'user declined'.",
      d: "Remove `refund_payment` and ask the model to describe the refund in text.",
    },
    whyWrong: {
      a: "An instruction in the description is a request to the model, not a guarantee; it may be ignored.",
      b: "The model's text does not control whether your code performs the action; the code must decide.",
      d: "That breaks automation and moves errors into manual copying; a checkpoint in code solves the task.",
    },
    explanation:
      "The model only requests a call — your code controls execution. So the gate for dangerous actions goes before execution, and a rejection is returned as a regular `tool_result` so the model can react.",
  },
  "dt-2-q15": {
    prompt: "A streaming request with client tools uses `eager_input_streaming: true`. What becomes your code's responsibility?",
    choices: {
      a: "Nothing new: the API still validates `input` before sending.",
      b: "Send a beta header by hand for each tool.",
      c: "Run the tool on every `input_json_delta` event.",
      d: "Assemble `input` from the deltas and validate it against the schema before executing.",
    },
    whyWrong: {
      a: "With the flag on, the API neither buffers nor validates the input, so `partial_json` may be incomplete or invalid.",
      b: "The flag is set on the tool definition; no beta header is needed.",
      c: "A delta is a JSON fragment; only a complete, validated input may be executed.",
    },
    explanation:
      "`eager_input_streaming` streams tool input as it is generated, without server-side buffering. The price is validation on your side: truncated or invalid JSON must not be executed.",
  },
  "dt-2-q16": {
    prompt: "The `read_logs` tool can return 2 MB of text. Which actions are correct?",
    choices: {
      a: "Return everything as is: the model will find what it needs.",
      b: "Add filters and pagination to the tool (level, time range, `limit`, cursor).",
      c: "Silently cut to the first 1000 characters.",
      d: "Truncate with an explicit note in the result: how much is shown, the total, and how to get the next part.",
    },
    whyWrong: {
      a: "A huge result floods the context, costs more on every iteration and may not fit in the window.",
      c: "Hidden truncation makes the model draw conclusions from partial data as if it were complete.",
    },
    explanation:
      "A tool result enters the context and is paid for again on every iteration. Filters and pagination reduce volume, and any truncation must be explicit in the result itself.",
  },
  // ── dt-3: tool_choice and parallel calls (extra pool) ──────────────────
  "dt-3-q8": {
    prompt: "The agent finishes with a summary for the user. Why set `tool_choice: {\"type\": \"none\"}` on that step instead of removing `tools` from the request?",
    choices: {
      a: "The model cannot call tools, and the `tools` prefix stays unchanged, so the cache is not broken.",
      b: "`none` only allows calling tools the model has already used in this conversation.",
      c: "`none` makes the response cheaper because tools stop being billed.",
      d: "`none` forces the model to return JSON.",
    },
    whyWrong: {
      b: "There is no such semantics: `none` forbids all calls.",
      c: "The definitions are still sent and count as input tokens.",
      d: "`none` only forbids calls; the response format is set by `output_config.format`.",
    },
    explanation:
      "`tools` are rendered at the very start of the prefix, so removing them invalidates the cache for the whole history. `tool_choice: none` achieves the goal — a text-only answer — without changing the prefix.",
  },
  "dt-3-q9": {
    prompt: "Which setting fits best?",
    scenario:
      "A pipeline classifies tickets on `claude-sonnet-5`. The result must always come through the `record_label` tool with the schema `{label, confidence}`. Right now, with `auto`, the model sometimes answers in text and the pipeline breaks.",
    choices: {
      a: "`tool_choice: {\"type\": \"none\"}`",
      b: "Keep `auto` and raise `max_tokens` so the model has room to reach the call.",
      c: "`tool_choice: {\"type\": \"tool\", \"name\": \"record_label\"}` and `strict: true` on the tool.",
      d: "Add `disable_parallel_tool_use: true` to `auto` so there is a single call.",
    },
    whyWrong: {
      a: "`none` forbids the call, guaranteeing exactly the behaviour that breaks the pipeline.",
      b: "The length limit does not affect the decision to call a tool.",
      d: "This limits the number of calls but does not force a call.",
    },
    explanation:
      "When the model supports forced choice, `tool` guarantees a call to the specific tool and `strict: true` guarantees schema-valid arguments. Together they give a reliable structured result.",
  },
  "dt-3-q10": {
    prompt: "The model called `get_user` and `get_orders` in parallel. The first succeeded, the second timed out. How do you return the results?",
    choices: {
      a: "Return only the successful result and say nothing about the error.",
      b: "Return two user messages: one with the success, one with the error.",
      c: "Keep retrying `get_orders` until it works before replying.",
      d: "One user message with two `tool_result` blocks: the success and one with `is_error: true` and a timeout description.",
    },
    whyWrong: {
      a: "Every `tool_use` needs a `tool_result`; without the second one the request gets a 400.",
      b: "Results of parallel calls should go together, in one message.",
      c: "Without a limit this can hang forever; the model should see the error and decide what to do.",
    },
    explanation:
      "Every call gets its own result, successful or not, and all of them go in one message. `is_error: true` lets the model retry just the failing call.",
  },
  "dt-3-q11": {
    prompt: "In which situations is `tool_choice: {\"type\": \"any\"}` more appropriate than `auto`?",
    choices: {
      a: "A chat assistant that should reply to greetings in text.",
      b: "A pipeline step where the model must choose one of several actions and text without an action is useless.",
      c: "The final step where the model writes a summary for the user.",
      d: "A router where each request class is a separate handler tool.",
    },
    whyWrong: {
      a: "`any` would force a tool call even where a plain text reply is needed.",
      c: "A summary needs text; `none` or `auto` fits better here.",
    },
    explanation:
      "`any` fits when a text reply without an action is a failure: routing, choosing a pipeline step. For conversation and summaries, leave the model free to answer in text.",
  },
  "dt-3-q12": {
    prompt: "You moved from `tool_choice: {\"type\": \"tool\"}` to `auto` with the instruction 'Use the `lookup` tool'. What must you add to the code?",
    choices: {
      a: "Nothing: a prompt instruction is equivalent to forced choice.",
      b: "`disable_parallel_tool_use: true`, to make the call mandatory.",
      c: "An assistant prefill with the tool name.",
      d: "A check that the response contains a `tool_use`, and a branch for when it does not.",
    },
    whyWrong: {
      a: "The instruction raises the chance of a call but does not guarantee it.",
      b: "The flag limits the number of calls but does not make a call mandatory under `auto`.",
      c: "Prefill is not allowed on current models and returns 400.",
    },
    explanation:
      "`auto` leaves the model free to answer in text. If your code relies on a call, it must check for a `tool_use` and have a plan for when there is none.",
  },
  "dt-3-q13": {
    prompt: "`runTool` throws for one of three parallel calls. What happens and how do you fix it?",
    choices: {
      a: "No harm: `Promise.all` returns the two successful results and the third is `undefined`.",
      b: "The SDK automatically catches the exception and marks the failed call as `is_error`.",
      c: "`Promise.all` rejects with no `tool_result` at all; catch each call's error and set `is_error`.",
      d: "Run the calls sequentially in a `for` loop — then one failure will not affect the others.",
    },
    whyWrong: {
      a: "`Promise.all` rejects on the first error and returns no partial results.",
      b: "In a manual loop the SDK never sees your exceptions; marking errors is your code's job.",
      d: "Sequential execution without try/catch still aborts the loop on the first exception.",
    },
    explanation:
      "Parallel execution must not become all-or-nothing. Wrap each call in try/catch (or use `Promise.allSettled`) and turn the error into a `tool_result` with `is_error: true`.",
  },
  "dt-3-q14": {
    prompt: "What is the simplest reliable fix?",
    scenario:
      "A booking agent has `reserve_seat` and `charge_card` tools. Sometimes the model calls them in parallel in one response, and your executor charges the card before the seat is confirmed. The business requires strict ordering.",
    choices: {
      a: "Ask in the `charge_card` description to call it only after a successful reservation.",
      b: "Sort parallel calls alphabetically before executing.",
      c: "Execute only the first `tool_use` in each response and ignore the rest.",
      d: "Enable `disable_parallel_tool_use: true` so calls come one at a time.",
    },
    whyWrong: {
      a: "The description raises the odds of the right order but does not guarantee it.",
      b: "Alphabetical order matches by accident and breaks with the first new tool.",
      c: "Ignored `tool_use` blocks without a `tool_result` cause a 400.",
    },
    explanation:
      "When actions depend on each other, parallelism hurts. One call per response ensures the model sees each step's result before the next; for extra safety, the payment can also check the reservation state in code.",
  },
  "dt-3-q15": {
    prompt: "With `auto`, a response contains a text block 'Let me check the weather in both cities' and two `tool_use` blocks. What do you do with the text?",
    choices: {
      a: "Remove it from history before the next request to avoid confusing the model.",
      b: "It is a model error: with `auto`, text alongside `tool_use` is not allowed.",
      c: "Move it into the `tool_result` so the model sees its plan.",
      d: "Keep it in the assistant message as is; optionally show it to the user as a status.",
    },
    whyWrong: {
      a: "There is no need to edit the model's turns: it changes the context and breaks the cache.",
      b: "With `auto` the model often writes a short sentence before calls — that is normal behaviour.",
      c: "`tool_result` is tool output; the model's text is already in its own turn.",
    },
    explanation:
      "Assistant messages are kept verbatim, with every block. Text before calls is a normal part of the turn and is handy to show as a progress indicator.",
  },
  "dt-3-q16": {
    prompt: "Which statements about parallel tool calls are correct?",
    choices: {
      a: "Each parallel call requires a separate API request.",
      b: "The model can return several `tool_use` blocks in one assistant message.",
      c: "Parallel calls are enabled with a separate beta header.",
      d: "They are enabled by default.",
      e: "The results of all calls are returned in one user message.",
    },
    whyWrong: {
      a: "All calls arrive in one response, and the results go back in one next request.",
      c: "Parallel tool use is on by default; you turn it off with `disable_parallel_tool_use`.",
    },
    explanation:
      "Parallel calls are the default behaviour: several `tool_use` blocks in one response, execution in your code (possibly concurrent) and all `tool_result` blocks in one message.",
  },
  // ── dt-4: Server tools (extra pool) ────────────────────────────────────
  "dt-4-q8": {
    prompt: "A model with web fetch tries to load a URL it 'guessed' from a site name and gets an error. Why?",
    choices: {
      a: "Web fetch only works with HTTPS domains from an Anthropic list.",
      b: "Code execution must be enabled first.",
      c: "Web fetch only loads URLs that have already appeared in the conversation.",
      d: "The model must pass the URL in base64.",
    },
    whyWrong: {
      a: "The restriction is not a platform domain list but where the URL came from.",
      b: "Web fetch does not depend on a separate code execution declaration.",
      d: "The URL is passed as a plain string; encoding is irrelevant.",
    },
    explanation:
      "Web fetch does not let the model visit arbitrary addresses: the URL must come from the conversation. For the model to find a page itself, pair it with web search.",
  },
  "dt-4-q9": {
    prompt: "Which of these tools is defined by Anthropic but executed by your code rather than the platform?",
    choices: {
      a: "Web search (`web_search`)",
      b: "Web fetch (`web_fetch`)",
      c: "Code execution (`code_execution`)",
      d: "Text editor (`str_replace_based_edit_tool`)",
    },
    whyWrong: {
      a: "Web search is a server tool executed by the platform.",
      b: "Web fetch also runs on Anthropic's side.",
      c: "Code execution runs in a platform container.",
    },
    explanation:
      "Anthropic-defined does not mean server-side. Bash, text editor and memory have a built-in schema the model is trained on, but their calls arrive as `tool_use` and are executed by your code.",
  },
  "dt-4-q10": {
    prompt: "How do you configure this?",
    scenario:
      "A documentation bot must answer only from the official sites `docs.example.com` and `api.example.com`. Right now web search sometimes cites forums and blogs.",
    choices: {
      a: "Set `allowed_domains` with these two domains in the web search declaration.",
      b: "Set both `allowed_domains` and `blocked_domains` with a list of forums.",
      c: "Write 'search only docs.example.com' in the system prompt.",
      d: "Filter citations in code after the response.",
    },
    whyWrong: {
      b: "The parameters are mutually exclusive: you set one of them, not both.",
      c: "A request does not restrict the tool; domain limits in its parameters are deterministic.",
      d: "The model has already built its answer on third-party sources; filtering afterwards does not remove their influence.",
    },
    explanation:
      "`allowed_domains` deterministically restricts where the tool searches; `blocked_domains` excludes domains instead. You use one of the two lists.",
  },
  "dt-4-q11": {
    prompt: "How do server tools differ from client tools?",
    choices: {
      a: "A server tool is declared via `type` and `name`, without your own `input_schema`.",
      b: "Their results arrive in the same response.",
      c: "For server tools you return a `tool_result` with `is_error` if something goes wrong.",
      d: "A client tool stops the response with `stop_reason: \"tool_use\"` and waits for your `tool_result`.",
      e: "Server tool results do not take up context and are not billed as tokens.",
    },
    whyWrong: {
      c: "The platform returns server tool errors in the result block; the client sends no `tool_result`.",
      e: "Results enter the model's context and count as tokens like any other content.",
    },
    explanation:
      "The difference is who executes: a client tool hands control back to your code, a server tool is run by the platform inside the request. Results of both take up context.",
  },
  "dt-4-q12": {
    prompt: "A developer declared `web_search_20260209` and, separately, `code_execution` 'so the model can filter search results with code'. What is wrong?",
    choices: {
      a: "Nothing: search results cannot be filtered without a separate code execution tool.",
      b: "Filtering is already built into this version; a second code execution only confuses the model.",
      c: "Combining these two tools requires a separate beta header.",
      d: "Code execution may only be declared together with web fetch, not web search.",
    },
    whyWrong: {
      a: "The new versions of the web tools have built-in dynamic filtering.",
      c: "Dynamic filtering needs neither a beta header nor a separate declaration.",
      d: "No such restriction exists; the problem is the duplicated environment.",
    },
    explanation:
      "The web search and web fetch versions with dynamic filtering run code to filter results by themselves. Add a separate code execution only when the app needs it for its own tasks.",
  },
  "dt-4-q13": {
    prompt: "Which statements about the tool search tool and `defer_loading` are correct?",
    choices: {
      a: "A tool with `defer_loading: true` does not enter the context until the model finds it via search.",
      b: "Found definitions replace the existing tools, so the cache is reset.",
      c: "The tool search tool itself must not be marked `defer_loading: true`.",
      d: "If every tool is deferred, the API returns 400.",
      e: "The model can never call deferred tools.",
    },
    whyWrong: {
      b: "Found schemas are appended to the request rather than swapped in, which preserves the cached prefix.",
      e: "Once search has found them, the model calls them like regular tools.",
    },
    explanation:
      "Tool search keeps a large catalogue out of context and loads the needed definitions on demand. At least one tool, including the search tool itself, must remain non-deferred.",
  },
  "dt-4-q14": {
    prompt: "What does the `allowed_callers` field in this definition give you, together with a declared code execution tool?",
    scenario:
      "A report needs `get_order` called for 300 orders and a total computed. Every result lands in context, and the agent spends hundreds of thousands of tokens on intermediate data needed only for the total.",
    choices: {
      a: "Allows only your app's administrators to call `get_order`.",
      b: "Moves execution of `get_order` to Anthropic's servers so your backend is not loaded.",
      c: "Disables `get_order` for regular model calls and turns it into a server tool.",
      d: "The model writes a script that calls `get_order`; results go to the script, only the total reaches the context.",
    },
    whyWrong: {
      a: "The field defines who may initiate the call within the request — the model or code in the container — not user roles.",
      b: "Your code still executes the tool; only where the result goes changes.",
      c: "It is not a server tool: your application still handles the call.",
    },
    explanation:
      "Programmatic tool calling lets code in the container call your tools. Intermediate results are processed by the script and only the final output returns to the model — saving tokens and latency.",
  },
  "dt-4-q15": {
    prompt: "A tool with `allowed_callers` (programmatic tool calling) was given `strict: true`. What should you know?",
    choices: {
      a: "Nothing special: strict simply guarantees valid arguments here too.",
      b: "strict automatically enables programmatic calling for every tool.",
      c: "Programmatic tool calling is incompatible with `strict: true`: you have to choose one.",
      d: "strict is mandatory, otherwise container code cannot call the tool.",
    },
    whyWrong: {
      a: "These features do not combine; you have to pick one.",
      b: "strict only concerns argument validation and does not affect other tools' `allowed_callers`.",
      d: "Programmatic calling does not require strict — in fact it is incompatible with it.",
    },
    explanation:
      "Programmatic tool calling has compatibility limits: in particular it does not work with `strict: true` or forced `tool_choice`. For such tools, validate inputs in code.",
  },
  "dt-4-q16": {
    prompt: "Why can a response with server tools come back with `stop_reason: \"pause_turn\"`?",
    choices: {
      a: "The model is waiting for your code to run a tool.",
      b: "The server-side tool loop hit its iteration limit, and the turn can be resumed.",
      c: "`max_tokens` was exhausted.",
      d: "A rate limit was hit and the request must be retried after `retry-after`.",
    },
    whyWrong: {
      a: "That is `tool_use`; your code does not run server tools.",
      c: "There is a separate `stop_reason: \"max_tokens\"` for that.",
      d: "A rate limit is HTTP 429, not a `stop_reason` in a successful response.",
    },
    explanation:
      "Server tools run in a server-side loop within the request. When the loop hits its limit, the response comes back with `pause_turn`, and you resume it by sending the history again.",
  },
  // ── dt-5: Structured output (extra pool) ───────────────────────────────
  "dt-5-q8": {
    prompt: "This code sometimes fails in `JSON.parse` even though `output_config.format` is used. What is missing?",
    choices: {
      a: "Wrap `JSON.parse` in try/catch and return `{}` on error.",
      b: "Add a beta header for structured outputs.",
      c: "Also pass the schema in the system prompt.",
      d: "A `stop_reason` check: with `max_tokens` the JSON may be truncated.",
    },
    whyWrong: {
      a: "An empty object silently hides the failure and passes false data downstream.",
      b: "The header is not the problem: the schema guarantee holds, just not for a truncated reply.",
      c: "Duplicating the schema in the prompt will not help if the reply was cut off.",
    },
    explanation:
      "The schema guarantee does not hold if generation was cut off by `max_tokens` — the JSON will be incomplete. Check `stop_reason` before parsing and leave headroom in `max_tokens`.",
  },
  "dt-5-q9": {
    prompt: "Which cause should you check first?",
    scenario:
      "A text moderation step uses `output_config.format` with the schema `{verdict, reasons}`. On some inputs the response does not parse against the schema, even though `max_tokens` has plenty of headroom.",
    choices: {
      a: "The schema is stale in the compilation cache and the API applies an older version.",
      b: "`stop_reason: \"refusal\"`: when the model declines for safety reasons, the output may not match the schema.",
      c: "The model cannot generate arrays in structured outputs.",
      d: "Structured outputs are incompatible with streaming, so it must be turned off.",
    },
    whyWrong: {
      a: "The cache speeds up repeated requests with the same schema but does not break conformance.",
      c: "Arrays are supported; only complex constraints on them are limited.",
      d: "Structured outputs work with streaming.",
    },
    explanation:
      "The schema guarantee has two known limits: `max_tokens` and `refusal`. Handle `stop_reason` explicitly, before parsing, and route such cases to a separate branch.",
  },
  "dt-5-q10": {
    prompt: "You added a document with `citations: {enabled: true}` and `output_config.format` to a request. What happens?",
    choices: {
      a: "The API returns 400: citations are incompatible with structured outputs.",
      b: "Citations automatically appear as a field inside the JSON.",
      c: "Citations are silently ignored and JSON comes back as usual.",
      d: "The format is silently ignored and text with citations comes back.",
    },
    whyWrong: {
      b: "Citations are not embedded in the JSON schema; the features do not combine.",
      c: "The incompatibility is not silently ignored — the request is rejected.",
      d: "The request does not run with part of its parameters; it is rejected entirely.",
    },
    explanation:
      "Citations and structured outputs are incompatible. If you need both sources and structure, add a field for references to your own schema or use two steps.",
  },
  "dt-5-q11": {
    prompt: "Which fix is most reliable?",
    scenario:
      "A request classifier returns `category` as a free string. Reports show 'Billing', 'billing', 'оплата' and 'payments' — all meaning the same thing.",
    choices: {
      a: "Normalise values in code with a synonym dictionary.",
      b: "Add the category list to the prompt and ask the model not to invent new values.",
      c: "Define `category` as an `enum` in the structured-output schema (with `other` if needed).",
      d: "Lower `temperature` to 0 so the model always picks the same variant.",
    },
    whyWrong: {
      a: "The dictionary will never be complete: the model will invent new variants.",
      b: "A request reduces variants but does not guarantee their absence.",
      d: "Determinism does not restrict the value set; the same input will just give the same variant.",
    },
    explanation:
      "A finite value set is an `enum`. With structured outputs the model cannot return a value outside the list, and an explicit `other` gives an honest outlet for unusual cases.",
  },
  "dt-5-q12": {
    prompt: "What does the SDK helper `messages.parse()` give you compared with a manual `messages.create()` + `JSON.parse`?",
    choices: {
      a: "It removes the need to check `stop_reason`.",
      b: "It validates the response against your schema (Pydantic / Zod).",
      c: "It returns an already parsed, typed object.",
      d: "It allows prefill again.",
      e: "It strips unsupported constraints (e.g. `minimum`) from the schema sent to the API and checks them client-side.",
    },
    whyWrong: {
      a: "A truncated reply or a refusal is still possible; you still need to check `stop_reason`.",
      d: "Prefill is banned at the API level; an SDK helper does not change that.",
    },
    explanation:
      "`messages.parse()` builds the schema from Pydantic/Zod, sends the compatible part to the API, checks the rest itself and returns a typed object. Handling `stop_reason` is still on you.",
  },
  "dt-5-q13": {
    prompt: "The API does not accept this structured-output schema. Why?",
    choices: {
      a: "Structured outputs do not support nested objects — the schema must be flattened.",
      b: "`required` cannot be combined with `additionalProperties` in the same schema object.",
      c: "The nested `address` object lacks `additionalProperties: false`, which is required on every object.",
      d: "The `name` field must be an `enum`.",
    },
    whyWrong: {
      a: "Nested objects are supported, but the same requirements apply to each.",
      b: "On the contrary, that is the standard pair for a closed schema.",
      d: "A free string is perfectly valid where the value set is unbounded.",
    },
    explanation:
      "Structured outputs require closed objects at every level: `additionalProperties: false` is needed at the root and in every nested object.",
  },
  "dt-5-q14": {
    prompt: "The first request with a new schema in `output_config.format` is noticeably slower than later ones. Why?",
    choices: {
      a: "Prompt caching kicks in and writes the schema to the cache.",
      b: "The API checks the schema against every model.",
      c: "The model first generates without the schema and then regenerates.",
      d: "A new schema is compiled once; after that the same schema is served from a cache.",
    },
    whyWrong: {
      a: "The delay is not about prompt caching but about preparing the schema for constrained generation.",
      b: "The delay comes from compiling the schema, not from such a check.",
      c: "Generation is constrained from the start; there is no second pass.",
    },
    explanation:
      "Constrained generation needs the schema compiled. The first request pays for it in latency, later ones with the same schema do not, so keep schemas stable.",
  },
  "dt-5-q15": {
    prompt: "What should you do?",
    scenario:
      "A contract extractor returns schema-valid JSON with `start_date` and `end_date` fields. An audit found that in 2% of records `end_date` is earlier than `start_date`.",
    choices: {
      a: "Check cross-field rules in code and, on violation, retry with a specific error.",
      b: "Add `minimum` for the dates to the schema.",
      c: "Nothing: the structured-output schema already guarantees correct data.",
      d: "Automatically swap the dates if they are in the wrong order.",
    },
    whyWrong: {
      b: "Numeric constraints are not supported and cannot compare one field with another.",
      c: "The schema guarantees shape, not logical consistency of values.",
      d: "Silent correction can record an extraction error as fact.",
    },
    explanation:
      "Structured outputs guarantee syntax and types, not semantics. Cross-field rules are checked in code, and a retry with a specific error gives the model a chance to correct itself.",
  },
  "dt-5-q16": {
    prompt: "What does `output_config.format` guarantee when the response ended with `stop_reason: \"end_turn\"`?",
    choices: {
      a: "That the values are logically correct (e.g. the total matches the line items).",
      b: "That the response is valid JSON that parses.",
      c: "That every field in `required` is present.",
      d: "That the same holds for `stop_reason: \"max_tokens\"`.",
      e: "That `enum` field values belong to the list.",
    },
    whyWrong: {
      a: "The schema checks neither meaning nor relations between fields.",
      d: "Truncated generation does not guarantee complete JSON.",
    },
    explanation:
      "The schema guarantees shape: valid JSON, required fields, types and `enum`. Semantic correctness is checked by code, and truncated replies must be filtered out by `stop_reason`.",
  },
  // ── dt-boss: A tool-using agent (extra pool) ───────────────────────────
  "dt-boss-q6": {
    prompt: "What should be fixed first?",
    scenario:
      "A code review agent calls `list_files` and `read_file`. On a large monorepo `list_files` returns 40,000 paths, and after just 5 iterations the context is nearly full and answer quality drops.",
    choices: {
      a: "Switch to a model with a larger context window so there is enough room.",
      b: "Compress the `list_files` result with zip and base64 to reduce its size.",
      c: "Give `list_files` filters, a limit and pagination, and mark truncation explicitly.",
      d: "Delete every message older than 3 iterations from history.",
    },
    whyWrong: {
      a: "A bigger window postpones the problem, but every iteration still costs more and the noise still hurts the model.",
      b: "The model cannot read compressed data, and base64 only increases the token count.",
      d: "Arbitrary deletion breaks `tool_use`/`tool_result` pairs and loses important context.",
    },
    explanation:
      "Context is best saved at the source: the tool returns exactly what is needed, with filters and pagination. Context management (context editing, compaction) is the next layer, not a substitute.",
  },
  "dt-boss-q7": {
    prompt: "Which approach makes the most sense?",
    scenario:
      "A team is building an agent with four custom tools in Python. No special transport or unusual requests are needed, but `delete_record` requires human approval.",
    choices: {
      a: "The SDK Tool Runner, with approval inside the `delete_record` function ('user declined' on rejection).",
      b: "Only a manual loop, because the Tool Runner executes tools with no way to intervene.",
      c: "Make `delete_record` a server tool so the platform asks for approval.",
      d: "Drop tools and ask the model to return an action plan as text.",
    },
    whyWrong: {
      b: "Approval can live inside the tool function or in the runner's hooks; a manual loop is not required here.",
      c: "Custom tools do not become server tools; execution and approval are on your side.",
      d: "You lose automation and structure; a gate on one action solves the task more simply.",
    },
    explanation:
      "The Tool Runner is a sensible default for an agent with custom tools. It does not take away control over dangerous actions: the gate goes in the tool function or in per-step hooks.",
  },
  "dt-boss-q8": {
    prompt: "Put the steps of one iteration of a robust agent loop in the correct order.",
    choices: {
      a: "Execute all `tool_use` blocks (dangerous ones after approval), catching errors.",
      b: "Append the whole `res.content` to history as an assistant message.",
      c: "Send the request with `tools` and the full history.",
      d: "Append all `tool_result` blocks as one user message and increment the iteration counter.",
      e: "Check `stop_reason`: if it is not `tool_use`, finish or handle it separately.",
    },
    explanation:
      "First store the model's response, then branch on `stop_reason`, and run tools only for `tool_use`. The iteration counter at the end lets you stop the loop in time.",
  },
  "dt-boss-q9": {
    prompt: "How should the dispatcher react to an unknown tool name?",
    scenario:
      "After removing the obsolete `legacy_export` tool, the model in long sessions sometimes still asks to call it (it appears in old history). The dispatcher throws `KeyError` and the session crashes.",
    choices: {
      a: "Silently skip the call and continue the loop without a result.",
      b: "Call the tool with the most similar name, for example `export`.",
      c: "End the session and show the user an error message.",
      d: "Return `is_error`: '`legacy_export` is unavailable; available: …'.",
    },
    whyWrong: {
      a: "Without a `tool_result` the next request gets a 400.",
      b: "Guessing can perform the wrong action with side effects.",
      c: "The model could correct itself if it saw the error.",
    },
    explanation:
      "An unknown tool is just another kind of tool error. A structured reply listing the available options lets the model choose the right path instead of crashing the session.",
  },
  "dt-boss-q10": {
    prompt: "A tool runs without `strict`, and the model sent `{\"days\": \"seven\"}` instead of a number. How should the code react?",
    choices: {
      a: "Substitute the default `days=7` and run.",
      b: "Raise and end the loop.",
      c: "Return a `tool_result` with `is_error: true` and the validation error text.",
      d: "Send the request again unchanged.",
    },
    whyWrong: {
      a: "Silent substitution hides the error and may produce the wrong result.",
      b: "The model will not see the error and cannot fix the call.",
      d: "Without information about the error, a retry gives the same result.",
    },
    explanation:
      "A validation error is a useful signal for the model: with a specific message it usually fixes the arguments on the next try. For critical tools also enable `strict: true`.",
  },
  "dt-boss-q11": {
    prompt: "What should change to make this safe?",
    scenario:
      "An analyst agent has a `run_sql` tool that runs arbitrary SQL against the production DB as a service user with full privileges. The tool description says: 'SELECT only. Never run DELETE or UPDATE.'",
    choices: {
      a: "Strengthen the wording in the tool description and repeat the ban in the system prompt.",
      b: "Enable `strict: true` for `run_sql` so the model cannot send dangerous queries.",
      c: "A read-only user with a timeout and row limit; writes via narrow tools with approval.",
      d: "Filter out queries containing DELETE or UPDATE in code with a regular expression.",
    },
    whyWrong: {
      a: "Any instruction is a request to the model; an injection or a mistake will bypass it.",
      b: "strict checks that `query` is a string, not that the query is safe.",
      d: "A blocklist is easy to bypass (`TRUNCATE`, `DROP`, CTEs and so on); restricting privileges is more reliable.",
    },
    explanation:
      "Tool safety must come from privileges and code, not description text. Least privilege plus narrow tools for dangerous actions limit the damage even when the model errs.",
  },
  "dt-boss-q12": {
    prompt: "An agent makes up to 30 iterations with the same set of 20 tools and a long system prompt. What is the simplest way to cut input token costs?",
    choices: {
      a: "Send `tools` only in the first request; after that the model remembers them.",
      b: "Prompt caching of the stable `tools` + `system` prefix, verified via `cache_read_input_tokens`.",
      c: "Shuffle the tools every iteration so the model does not 'get used to' the order.",
      d: "Cut the descriptions of all 20 tools down to one word each.",
    },
    whyWrong: {
      a: "The API is stateless: without `tools` in later requests the model cannot call tools.",
      c: "Shuffling breaks the cache and does not improve selection.",
      d: "The savings are tiny compared with caching, and tool selection quality drops sharply.",
    },
    explanation:
      "In an agent loop `tools` and `system` repeat in every request — an ideal cache candidate. The prefix must be byte-for-byte stable, and `cache_read_input_tokens` confirms the hits.",
  },
};
