import type { QuestionSource } from "@/lib/content/types";

const d = "dev-api" as const;

/** Додатковий пул питань домену: розширює вибірку, щоб спроби не повторювались. */
export const questionsMore: QuestionSource[] = [
  // ── da-1: Messages API (додатковий пул) ──────────────────────────────────
  {
    id: "da-1-q9",
    domainId: d,
    levelId: "da-1",
    kind: "single",
    difficulty: 3,
    prompt: "Які заголовки потрібні для сирого HTTP-запиту до Messages API з API-ключем?",
    choices: [
      { id: "a", text: "`Authorization: Bearer <key>` і `content-type: application/json`", whyWrong: "API-ключ передають у `x-api-key`; `Authorization: Bearer` використовують для OAuth-токенів, і без `anthropic-version` запит однаково не пройде." },
      { id: "b", text: "`x-api-key` і `anthropic-model`", whyWrong: "Модель вказують у тілі запиту полем `model`, заголовка `anthropic-model` немає." },
      { id: "c", text: "Лише `x-api-key`: решту SDK додає сам.", whyWrong: "Питання про сирий HTTP: без SDK ніхто не додасть `anthropic-version` за вас." },
      { id: "d", text: "`x-api-key`, `anthropic-version` і `content-type: application/json`" },
    ],
    correct: ["d"],
    explanation:
      "Ключ іде в `x-api-key`, версія API — в `anthropic-version` (наприклад, `2023-06-01`), тіло — JSON. SDK ставить ці заголовки автоматично.",
    codexRef: "dev-api-messages",
  },
  {
    id: "da-1-q10",
    domainId: d,
    levelId: "da-1",
    kind: "single",
    difficulty: 2,
    prompt: "Що фіксує заголовок `anthropic-version: 2023-06-01`?",
    choices: [
      { id: "a", text: "Версію формату й поведінки API, щоб зміни протоколу не ламали ваш клієнт." },
      { id: "b", text: "Знімок моделі, випущений до цієї дати.", whyWrong: "Модель вибирає поле `model`; заголовок версії не впливає на те, яка модель відповідає." },
      { id: "c", text: "Дату, до якої діє ваш API-ключ.", whyWrong: "Термін дії ключа ніяк не пов'язаний із цим заголовком." },
      { id: "d", text: "Набір увімкнених бета-функцій.", whyWrong: "Бета-функції вмикають окремим заголовком `anthropic-beta`." },
    ],
    correct: ["a"],
    explanation:
      "`anthropic-version` — версія контракту API, а не моделі. Бета-можливості вмикає `anthropic-beta`, модель — поле `model` у тілі.",
    codexRef: "dev-api-messages",
  },
  {
    id: "da-1-q11",
    domainId: d,
    levelId: "da-1",
    kind: "single",
    difficulty: 2,
    prompt: "Як передати зображення з диска в запиті до Messages API?",
    code: { lang: "python", source: "import base64\n\ndata = base64.standard_b64encode(open(\"chart.png\", \"rb\").read()).decode()" },
    choices: [
      { id: "a", text: "Прикріпити файл як multipart/form-data до того самого запиту.", whyWrong: "Messages API приймає лише JSON; бінарні дані вкладають у тіло як base64 або посилаються на них." },
      { id: "b", text: "Вставити base64-рядок у текстовий блок після слова `image:`.", whyWrong: "Модель отримає це як текст, а не як зображення, і даремно витратить тисячі токенів." },
      { id: "c", text: "Додати в `content` блок `{\"type\": \"image\", \"source\": {\"type\": \"base64\", \"media_type\": \"image/png\", \"data\": data}}`." },
      { id: "d", text: "Покласти base64 у параметр `system`.", whyWrong: "Зображення — це блок у `content` повідомлення, а не частина системного промпта." },
    ],
    correct: ["c"],
    explanation:
      "Зображення — окремий блок `image` із джерелом `base64` (плюс `media_type`) або `url`. Його кладуть у `content` повідомлення `user`, зазвичай перед текстовим питанням.",
    codexRef: "dev-api-messages",
  },
  {
    id: "da-1-q12",
    domainId: d,
    levelId: "da-1",
    kind: "scenario",
    difficulty: 2,
    scenario:
      "Сервіс має відповідати на питання за 40-сторінковим PDF-договором. Зараз код витягує текст з PDF бібліотекою і втрачає таблиці та структуру.",
    prompt: "Який спосіб передачі документа кращий?",
    choices: [
      { id: "a", text: "Передати PDF блоком `document` з `media_type: \"application/pdf\"` у base64 перед текстовим питанням." },
      { id: "b", text: "Надіслати кожну сторінку окремим запитом і склеїти відповіді.", whyWrong: "Питання про договір часто зачіпають кілька сторінок; окремі запити втрачають зв'язки між ними." },
      { id: "c", text: "Вставити PDF як base64 у текстовий блок.", whyWrong: "Base64 у тексті модель не розбирає як документ — це просто набір символів." },
      { id: "d", text: "Конвертувати PDF у зображення однієї великої сторінки.", whyWrong: "Велике зображення зменшують, і текст стає нечитабельним; блок `document` обробляє сторінки сам." },
    ],
    correct: ["a"],
    explanation:
      "Блок `document` дає моделі і текст, і візуальний вигляд сторінок, тож таблиці й макет зберігаються. Документ кладуть перед питанням в одному повідомленні `user`.",
    codexRef: "dev-api-messages",
  },
  {
    id: "da-1-q13",
    domainId: d,
    levelId: "da-1",
    kind: "multi",
    difficulty: 3,
    prompt: "Що містить об'єкт відповіді Messages API?",
    choices: [
      { id: "a", text: "`conversation_id` для продовження розмови", whyWrong: "Такого поля немає: API не зберігає розмову, продовження — це новий запит з повною історією." },
      { id: "b", text: "Повну історію розмови разом із новою відповіддю", whyWrong: "Повертається лише нове повідомлення `assistant`; історію збираєте ви." },
      { id: "c", text: "`stop_reason` — чому модель зупинилась" },
      { id: "d", text: "`usage` з кількістю вхідних і вихідних токенів" },
      { id: "e", text: "`id`, `role: \"assistant\"` і `model`" },
    ],
    correct: ["c", "d", "e"],
    explanation:
      "Відповідь — одне повідомлення `assistant`: `id`, `model`, масив `content`, `stop_reason`, `stop_sequence` і `usage`. Стану розмови на сервері немає.",
    codexRef: "dev-api-messages",
  },
  {
    id: "da-1-q14",
    domainId: d,
    levelId: "da-1",
    kind: "single",
    difficulty: 2,
    prompt: "Звідки клієнт `anthropic.Anthropic()` у Python бере API-ключ, якщо його не передали явно?",
    choices: [
      { id: "a", text: "З файлу `.anthropic` у домашньому каталозі; інших джерел немає.", whyWrong: "Такого фіксованого файла SDK не читає; основне джерело — змінна оточення." },
      { id: "b", text: "Нізвідки: без аргументу `api_key` конструктор кидає помилку.", whyWrong: "Конструктор без аргументів — рекомендований спосіб: SDK сам знаходить облікові дані в оточенні." },
      { id: "c", text: "З першого повідомлення в `messages`.", whyWrong: "Облікові дані ніколи не передаються у вмісті повідомлень." },
      { id: "d", text: "Зі змінної оточення `ANTHROPIC_API_KEY`." },
    ],
    correct: ["d"],
    explanation:
      "SDK читає ключ з `ANTHROPIC_API_KEY`, тож його не треба зашивати в код чи коміт. Явний `api_key=` потрібен лише тоді, коли ключ приходить з іншого сховища секретів.",
    codexRef: "dev-api-messages",
  },
  {
    id: "da-1-q15",
    domainId: d,
    levelId: "da-1",
    kind: "single",
    difficulty: 2,
    prompt: "Чим `\"content\": \"Привіт\"` відрізняється від `\"content\": [{\"type\": \"text\", \"text\": \"Привіт\"}]`?",
    choices: [
      { id: "a", text: "Рядок передає текст як system-інструкцію, масив — як репліку.", whyWrong: "Роль задає поле `role`, а не форма `content`." },
      { id: "b", text: "Нічим по суті: рядок — скорочений запис одного текстового блоку; масив потрібен для кількох блоків, зображень чи `cache_control`." },
      { id: "c", text: "Рядок токенізується дешевше.", whyWrong: "Токенізується той самий текст; різниця лише у формі JSON." },
      { id: "d", text: "Масив дозволений лише для повідомлень `assistant`.", whyWrong: "Масив блоків — основна форма й для `user`: саме так передають зображення та `tool_result`." },
    ],
    correct: ["b"],
    explanation:
      "Рядковий `content` еквівалентний масиву з одним блоком `text`. Масив потрібен, коли треба змішати типи блоків або позначити блок `cache_control`.",
    codexRef: "dev-api-messages",
  },
  {
    id: "da-1-q16",
    domainId: d,
    levelId: "da-1",
    kind: "scenario",
    difficulty: 3,
    scenario:
      "У застосунку-помічнику вартість кожного наступного повідомлення в довгій розмові помітно більша за попереднє, хоча користувачі пишуть короткі репліки.",
    prompt: "Що пояснює це зростання і як його стримати?",
    choices: [
      { id: "a", text: "Кожен запит несе всю історію як вхідні токени; допоможуть prompt caching стабільного префікса й стискання або обрізання старих ходів." },
      { id: "b", text: "Модель довше «думає» в довгій розмові; треба зменшити `max_tokens`.", whyWrong: "`max_tokens` обмежує лише вихід; зростання йде від вхідних токенів історії." },
      { id: "c", text: "API додає націнку за тривалість сесії.", whyWrong: "Сесій в API немає; оплата — лише за токени конкретного запиту." },
      { id: "d", text: "Це помилка підрахунку: перезапуск клієнта SDK обнулить лічильник.", whyWrong: "Лічильника на боці клієнта немає; `usage` відображає реальний розмір кожного запиту." },
    ],
    correct: ["a"],
    explanation:
      "Stateless-історія означає, що N-й хід містить усі попередні, тож сумарна вартість росте приблизно квадратично. Кешування здешевлює повторюваний префікс, а стискання тримає історію компактною.",
    codexRef: "dev-api-messages",
  },
  {
    id: "da-1-q17",
    domainId: d,
    levelId: "da-1",
    kind: "single",
    difficulty: 3,
    prompt: "Запит повертає 400. Що в ньому не так?",
    code: { lang: "python", source: "client.messages.create(\n    model=\"claude-haiku-4-5-20251001\",\n    max_tokens=512,\n    messages=[\n        {\"role\": \"assistant\", \"content\": \"Вітаю! Чим допомогти?\"},\n        {\"role\": \"user\", \"content\": \"Підсумуй цей лист.\"},\n    ],\n)" },
    choices: [
      { id: "a", text: "Українська мова в `content` вимагає окремого параметра `language`.", whyWrong: "Параметра `language` немає; модель працює з будь-якою мовою в тексті." },
      { id: "b", text: "`max_tokens=512` замало для цієї моделі.", whyWrong: "Мале `max_tokens` не дає 400, а лише може обрізати відповідь зі `stop_reason: \"max_tokens\"`." },
      { id: "c", text: "Бракує параметра `system`.", whyWrong: "`system` необов'язковий." },
      { id: "d", text: "Масив `messages` мусить починатися з повідомлення `user`." },
    ],
    correct: ["d"],
    explanation:
      "Розмова в Messages API починається з репліки користувача. Привітання бота, якщо воно потрібне моделі, краще описати в `system` або перенести в перше повідомлення `user`.",
    codexRef: "dev-api-messages",
  },
  {
    id: "da-1-q18",
    domainId: d,
    levelId: "da-1",
    kind: "order",
    difficulty: 3,
    prompt: "Розставте кроки, щоб спитати модель про скриншот із диска.",
    choices: [
      { id: "a", text: "Прочитати байти файла" },
      { id: "b", text: "Закодувати їх у base64 без переносів рядків" },
      { id: "c", text: "Зібрати блок `image` з `media_type` і `data`" },
      { id: "d", text: "Покласти блок `image`, а за ним текстове питання в `content` повідомлення `user`" },
      { id: "e", text: "Викликати `messages.create`" },
    ],
    correct: ["a", "b", "c", "d", "e"],
    explanation:
      "Бінарні дані потрапляють у JSON як base64 в блоці `image` із правильним `media_type`. Зображення перед питанням — рекомендований порядок у `content`.",
    codexRef: "dev-api-messages",
  },
  {
    id: "da-1-q19",
    domainId: d,
    levelId: "da-1",
    kind: "multi",
    difficulty: 2,
    prompt: "Що правда про параметр `system`?",
    choices: [
      { id: "a", text: "Він може бути рядком або масивом текстових блоків." },
      { id: "b", text: "Він тарифікується як вхідні токени в кожному запиті." },
      { id: "c", text: "Сервер зберігає його між запитами, тож надсилати його треба лише раз.", whyWrong: "API не має стану: `system` треба передавати в кожному запиті." },
      { id: "d", text: "Він не займає місця в контекстному вікні.", whyWrong: "Системний промпт — частина входу й займає контекст так само, як повідомлення." },
      { id: "e", text: "На його текстовий блок можна поставити `cache_control`." },
    ],
    correct: ["a", "b", "e"],
    explanation:
      "`system` — звичайна частина входу: займає контекст і коштує токенів щоразу. Форма масиву блоків дає змогу кешувати великий стабільний системний промпт.",
    codexRef: "dev-api-messages",
  },
  {
    id: "da-1-q20",
    domainId: d,
    levelId: "da-1",
    kind: "scenario",
    difficulty: 2,
    scenario:
      "Команда переносить чат з іншого LLM-API, де системна інструкція була першим повідомленням масиву з роллю `system`. Після заміни клієнта на Anthropic SDK запити почали падати з 400.",
    prompt: "Яка зміна потрібна?",
    choices: [
      { id: "a", text: "Перейменувати роль на `developer`.", whyWrong: "Ролі `developer` у Messages API немає; діалог будується з повідомлень `user` і `assistant`." },
      { id: "b", text: "Об'єднати інструкцію з першим повідомленням `assistant`.", whyWrong: "Розмова мусить починатися з `user`, а інструкції в репліці асистента не мають статусу системного промпта." },
      { id: "c", text: "Винести інструкцію в параметр `system`, а в `messages` лишити тільки `user`/`assistant`." },
      { id: "d", text: "Додати заголовок `anthropic-beta: system-role`.", whyWrong: "Такого бета-прапорця немає; основний системний промпт і так має окреме поле." },
    ],
    correct: ["c"],
    explanation:
      "Messages API розділяє операторську інструкцію (`system`) і діалог (`messages`). Під час міграції з інших API це найчастіша причина 400.",
    codexRef: "dev-api-messages",
  },
  // ── da-2: Моделі та параметри (додатковий пул) ───────────────────────────
  {
    id: "da-2-q9",
    domainId: d,
    levelId: "da-2",
    kind: "single",
    difficulty: 3,
    prompt: "Старий код вмикає thinking так: `thinking={\"type\": \"enabled\", \"budget_tokens\": 8000}`. Що станеться на `claude-sonnet-5`?",
    choices: [
      { id: "a", text: "Параметр мовчки проігнорують, і модель відповість без thinking.", whyWrong: "Застарілу форму не ігнорують мовчки, а відхиляють з помилкою." },
      { id: "b", text: "Бюджет автоматично конвертується в `effort: \"medium\"`.", whyWrong: "Автоконвертації немає; міграцію треба зробити в коді." },
      { id: "c", text: "Модель думатиме рівно 8000 токенів.", whyWrong: "Навіть на старих моделях бюджет був стелею, а не точною кількістю; на цій моделі форма взагалі не приймається." },
      { id: "d", text: "API поверне 400; треба перейти на `thinking: {type: \"adaptive\"}` і керувати глибиною через `effort`." },
    ],
    correct: ["d"],
    explanation:
      "Фіксований `budget_tokens` на найновіших моделях прибрано. Адаптивне thinking саме вирішує, скільки думати, а `effort` задає загальну глибину.",
    codexRef: "dev-api-models-params",
  },
  {
    id: "da-2-q10",
    domainId: d,
    levelId: "da-2",
    kind: "scenario",
    difficulty: 3,
    scenario:
      "Агент з увімкненим thinking викликає інструменти. Щоб зекономити токени, код перед наступним запитом видаляє з відповіді `assistant` блоки `thinking` і лишає тільки `text` і `tool_use`.",
    prompt: "Що правильно?",
    choices: [
      { id: "a", text: "Це безпечна оптимізація: thinking потрібен лише для одного ходу.", whyWrong: "Посеред циклу інструментів модель спирається на свої попередні міркування; їх видалення ламає продовження." },
      { id: "b", text: "Треба замінити блоки `thinking` текстовим підсумком міркувань.", whyWrong: "Змінені чи підмінені блоки thinking не пройдуть перевірку підпису; їх передають лише без змін." },
      { id: "c", text: "Передавати блоки `thinking` назад без змін разом з рештою `content`." },
      { id: "d", text: "Вимкнути thinking на ходах з інструментами.", whyWrong: "Це лікує симптом ціною якості; правильне рішення — просто не чіпати блоки." },
    ],
    correct: ["c"],
    explanation:
      "Блоки `thinking` несуть підпис і належать до ходу моделі. У циклі tool use їх повертають разом з `tool_use` без жодних змін — найпростіше додавати `response.content` цілком.",
    codexRef: "dev-api-models-params",
  },
  {
    id: "da-2-q11",
    domainId: d,
    levelId: "da-2",
    kind: "single",
    difficulty: 2,
    prompt: "Відповідь обірвалась посеред речення, `stop_reason: \"max_tokens\"`. Що це означає?",
    choices: [
      { id: "a", text: "Модель досягла стелі `max_tokens` і не завершила відповідь; її треба збільшити або скоротити задачу." },
      { id: "b", text: "Вичерпано контекстне вікно моделі, треба змінити модель.", whyWrong: "Це ліміт виходу з вашого запиту, а не переповнення контексту." },
      { id: "c", text: "Модель вирішила, що відповідь завершена.", whyWrong: "Природне завершення позначається `end_turn`." },
      { id: "d", text: "Сталася помилка сервера, запит треба повторити без змін.", whyWrong: "Це успішна відповідь з кодом 200; повтор з тим самим `max_tokens` дасть те саме обрізання." },
    ],
    correct: ["a"],
    explanation:
      "`max_tokens` — жорстка стеля. Код має перевіряти `stop_reason` перед використанням результату: обрізаний JSON чи код не можна просто розібрати.",
    codexRef: "dev-api-models-params",
  },
  {
    id: "da-2-q12",
    domainId: d,
    levelId: "da-2",
    kind: "single",
    difficulty: 2,
    prompt: "Як програмно дізнатися контекстне вікно й максимальний вихід моделі?",
    choices: [
      { id: "a", text: "Прочитати поле `context_window` з будь-якої відповіді Messages API.", whyWrong: "У відповіді Messages API такого поля немає." },
      { id: "b", text: "Викликати Models API (`GET /v1/models/{id}`) і прочитати `max_input_tokens` та `max_tokens`." },
      { id: "c", text: "Надіслати запит із дуже великим `max_tokens` і прочитати текст помилки.", whyWrong: "Парсити тексти помилок крихко й марнує запити; для цього є окремий API." },
      { id: "d", text: "Порахувати за назвою моделі: число в назві — розмір вікна в тисячах токенів.", whyWrong: "Число в назві — версія моделі, а не розмір вікна." },
    ],
    correct: ["b"],
    explanation:
      "Models API повертає можливості моделі: `max_input_tokens` (вікно контексту) і `max_tokens` (стеля виходу). Це краще за хардкод, бо значення відрізняються між моделями.",
    codexRef: "dev-api-models-params",
  },
  {
    id: "da-2-q13",
    domainId: d,
    levelId: "da-2",
    kind: "scenario",
    difficulty: 3,
    scenario:
      "Чат на `claude-sonnet-5` з `thinking: {type: \"adaptive\"}` стрімить міркування користувачу. Блоки `thinking` приходять, але їхній текст порожній, і користувач бачить довгу паузу.",
    prompt: "Що змінити?",
    choices: [
      { id: "a", text: "Нічого: модель насправді не думала.", whyWrong: "Блоки приходять, отже thinking відбувається й оплачується; просто текст не показується." },
      { id: "b", text: "Повернутися до `budget_tokens`, щоб побачити сирі міркування.", whyWrong: "`budget_tokens` на цій моделі дає 400, а сирий chain of thought не повертається за жодних налаштувань." },
      { id: "c", text: "Збільшити `max_tokens`, щоб thinking вмістився.", whyWrong: "Порожній текст не пов'язаний з лімітом; це налаштування показу." },
      { id: "d", text: "Явно вказати `thinking: {type: \"adaptive\", display: \"summarized\"}`." },
    ],
    correct: ["d"],
    explanation:
      "На новіших моделях за замовчуванням `display: \"omitted\"`: блоки є, текст порожній. `\"summarized\"` повертає читабельний підсумок; оплата thinking від цього не змінюється.",
    codexRef: "dev-api-models-params",
  },
  {
    id: "da-2-q14",
    domainId: d,
    levelId: "da-2",
    kind: "single",
    difficulty: 2,
    prompt: "Як тарифікуються токени thinking?",
    choices: [
      { id: "a", text: "Безкоштовно, якщо `display: \"omitted\"`.", whyWrong: "`display` керує лише видимістю; міркування відбуваються й оплачуються однаково." },
      { id: "b", text: "Як вхідні токени наступного запиту.", whyWrong: "Токени thinking генерує модель у поточному запиті, тож вони рахуються як вихідні саме тут." },
      { id: "c", text: "Як вихідні токени, і вони входять у `max_tokens`." },
      { id: "d", text: "За окремим тарифом, який не входить в `usage`.", whyWrong: "Окремого тарифу немає; вони враховані в `output_tokens`." },
    ],
    correct: ["c"],
    explanation:
      "Thinking — це згенеровані моделлю токени, тож вони йдуть у `output_tokens` і займають місце в межах `max_tokens`. Для задач з глибоким мисленням `max_tokens` треба закладати з запасом.",
    codexRef: "dev-api-models-params",
  },
  {
    id: "da-2-q15",
    domainId: d,
    levelId: "da-2",
    kind: "multi",
    difficulty: 2,
    prompt: "Що правда про `stop_sequences`?",
    choices: [
      { id: "a", text: "Це масив звичайних рядків." },
      { id: "b", text: "Збіг дає `stop_reason: \"stop_sequence\"`." },
      { id: "c", text: "Можна передати регулярні вирази, наприклад `\"\\d+\\.\"`.", whyWrong: "Послідовності порівнюються як літеральні рядки, регулярні вирази не підтримуються." },
      { id: "d", text: "Стоп-послідовність перевіряється і у вхідних повідомленнях, обрізаючи їх.", whyWrong: "Вона діє лише на згенерований вихід; вхід не змінюється." },
      { id: "e", text: "Знайдена послідовність не додається до тексту відповіді." },
    ],
    correct: ["a", "b", "e"],
    explanation:
      "`stop_sequences` зупиняє генерацію на першому збігу будь-якого з рядків. Який саме рядок спрацював, видно в полі `stop_sequence` відповіді.",
    codexRef: "dev-api-models-params",
  },
  {
    id: "da-2-q16",
    domainId: d,
    levelId: "da-2",
    kind: "order",
    difficulty: 2,
    prompt: "Розставте кроки вибору моделі для нової фічі.",
    choices: [
      { id: "a", text: "Сформулювати задачу й критерії якості" },
      { id: "b", text: "Зібрати eval-набір з реалістичних прикладів" },
      { id: "c", text: "Прогнати найдешевшу модель-кандидата" },
      { id: "d", text: "Порівняти з сильнішою моделлю або вищим `effort`" },
      { id: "e", text: "Обрати найдешевшу конфігурацію, що проходить поріг якості" },
    ],
    correct: ["a", "b", "c", "d", "e"],
    explanation:
      "Вибір моделі — інженерне рішення на даних: спершу критерії й eval, потім вимірювання від дешевого до дорогого. Інакше легко переплатити за Opus там, де вистачило б Haiku.",
    codexRef: "dev-api-models-params",
  },
  {
    id: "da-2-q17",
    domainId: d,
    levelId: "da-2",
    kind: "scenario",
    difficulty: 3,
    scenario:
      "Після переходу з `claude-opus-5` на `claude-opus-5-5` агент для рефакторингу став робити поверховіші зміни й рідше запускати тести. Промпт і інші параметри не змінювались; `effort` у запиті не вказаний.",
    prompt: "Що перевірити першим?",
    choices: [
      { id: "a", text: "Чи не зменшився контекст нової моделі.", whyWrong: "Контекстне вікно в цих моделей однакове; причина в налаштуванні старанності." },
      { id: "b", text: "Значення `effort` за замовчуванням: у нової моделі воно нижче, тож його варто задати явно (`high` чи `xhigh`)." },
      { id: "c", text: "Чи не треба повернути `temperature: 0`.", whyWrong: "Параметри семплінгу на цій моделі не приймаються взагалі." },
      { id: "d", text: "Чи не спрацьовує rate limit.", whyWrong: "Rate limit дає помилки 429, а не поверховіші відповіді." },
    ],
    correct: ["b"],
    explanation:
      "Покладатися на значення за замовчуванням під час міграції ризиковано: у `claude-opus-5-5` дефолтний `effort` — `medium`. Для кодингу й агентних задач його задають явно.",
    codexRef: "dev-api-models-params",
  },
  {
    id: "da-2-q18",
    domainId: d,
    levelId: "da-2",
    kind: "single",
    difficulty: 2,
    prompt: "Код на `claude-sonnet-5` отримує 400, бо останнім повідомленням передає `{\"role\": \"assistant\", \"content\": \"{\"}`, щоб змусити модель почати з JSON. Як отримати гарантований JSON?",
    choices: [
      { id: "a", text: "Поставити `stop_sequences: [\"}\"]`.", whyWrong: "Це обріже JSON на першій вкладеній дужці й нічого не гарантує щодо початку відповіді." },
      { id: "b", text: "Повторювати запит, доки 400 не зникне.", whyWrong: "Prefill на цих моделях не підтримується, тож 400 буде завжди." },
      { id: "c", text: "Додати в `system` фразу «відповідай лише JSON» і парсити що прийде.", whyWrong: "Інструкція підвищує шанси, але не гарантує валідність за схемою." },
      { id: "d", text: "Використати структурований вивід: `output_config.format` з JSON-схемою." },
    ],
    correct: ["d"],
    explanation:
      "Prefill останнього ходу `assistant` на сучасних моделях повертає 400. Гарантований формат дає структурований вивід (`output_config.format`) з JSON-схемою.",
    codexRef: "dev-api-models-params",
  },
  {
    id: "da-2-q19",
    domainId: d,
    levelId: "da-2",
    kind: "single",
    difficulty: 3,
    prompt: "На Haiku 4.5 thinking вмикають через `budget_tokens`. Який запит коректний?",
    choices: [
      { id: "a", text: "`max_tokens=16000`, `thinking={\"type\": \"enabled\", \"budget_tokens\": 4000}`" },
      { id: "b", text: "`max_tokens=2000`, `thinking={\"type\": \"enabled\", \"budget_tokens\": 4000}`", whyWrong: "`budget_tokens` мусить бути меншим за `max_tokens`, бо thinking входить у вихід." },
      { id: "c", text: "`max_tokens=16000`, `thinking={\"type\": \"enabled\", \"budget_tokens\": 256}`", whyWrong: "Мінімальний бюджет — 1024 токени; менше значення відхиляється." },
      { id: "d", text: "`max_tokens=16000`, `thinking={\"type\": \"adaptive\", \"budget_tokens\": 4000}`", whyWrong: "Адаптивний режим не приймає бюджету, а Haiku 4.5 використовує саме `enabled` з `budget_tokens`." },
    ],
    correct: ["a"],
    explanation:
      "Для моделей з `budget_tokens` діють два правила: бюджет щонайменше 1024 і менший за `max_tokens`. На найновіших моделях замість цього — адаптивне thinking з `effort`.",
    codexRef: "dev-api-models-params",
  },
  {
    id: "da-2-q20",
    domainId: d,
    levelId: "da-2",
    kind: "scenario",
    difficulty: 2,
    scenario:
      "Після деплою всі запити падають з помилкою `not_found_error`, у повідомленні — `model: claude-sonnet-5.0`. Ключ і мережа в порядку.",
    prompt: "Що сталося?",
    choices: [
      { id: "a", text: "Модель перевантажена, треба чекати.", whyWrong: "Перевантаження — це 529 `overloaded_error`, а не `not_found_error`." },
      { id: "b", text: "Ключ не має доступу до API, треба створити новий.", whyWrong: "Проблеми з ключем дають 401 `authentication_error`." },
      { id: "c", text: "Ідентифікатор моделі написано неправильно; правильний — `claude-sonnet-5`, а список доступних моделей дає `GET /v1/models`." },
      { id: "d", text: "Треба додати бета-заголовок для нової моделі.", whyWrong: "Для звичайної моделі бета-заголовок не потрібен; неіснуючий бета-прапорець дав би 400, а не 404." },
    ],
    correct: ["c"],
    explanation:
      "404 з `model: ...` у повідомленні означає, що модель не знайдена або недоступна вашій організації. Ідентифікатори пишуть через дефіси, без крапок; перевіряють їх через Models API.",
    codexRef: "dev-api-models-params",
  },
  // ── da-3: Streaming (додатковий пул) ─────────────────────────────────────
  {
    id: "da-3-q9",
    domainId: d,
    levelId: "da-3",
    kind: "single",
    difficulty: 2,
    prompt: "Де в потоці шукати лічильники токенів?",
    choices: [
      { id: "a", text: "Лише в останній `content_block_delta`.", whyWrong: "Дельти блоків не несуть `usage`." },
      { id: "b", text: "`message_start` несе `usage` з вхідними токенами, `message_delta` — кумулятивний `output_tokens`." },
      { id: "c", text: "Потік не повідомляє токенів; треба окремо викликати `count_tokens`.", whyWrong: "Потік повідомляє `usage`; `count_tokens` потрібен для оцінки до запиту." },
      { id: "d", text: "У HTTP-заголовках відповіді.", whyWrong: "Заголовки несуть ліміти й `request-id`, а не `usage` конкретної генерації." },
    ],
    correct: ["b"],
    explanation:
      "`usage` у streaming розподілений: вхід відомий одразу в `message_start`, вихід — у `message_delta`. Лічильник у `message_delta` кумулятивний, тож його не треба сумувати.",
    codexRef: "dev-api-streaming",
  },
  {
    id: "da-3-q10",
    domainId: d,
    levelId: "da-3",
    kind: "single",
    difficulty: 3,
    prompt: "Чому для запитів з великим `max_tokens` (десятки тисяч) рекомендують streaming навіть без UI?",
    choices: [
      { id: "a", text: "Довга генерація без жодних даних у з'єднанні ризикує впертися в HTTP-таймаути; SDK для таких значень вимагає або радить streaming." },
      { id: "b", text: "Streaming дешевший за тими самими токенами.", whyWrong: "Ціна однакова: токени ті самі." },
      { id: "c", text: "Без streaming `max_tokens` обрізається до 4096.", whyWrong: "API не обрізає `max_tokens` залежно від режиму; проблема в тривалості з'єднання." },
      { id: "d", text: "Лише streaming повертає `stop_reason`.", whyWrong: "`stop_reason` є в обох режимах." },
    ],
    correct: ["a"],
    explanation:
      "Streaming тримає з'єднання активним, поки модель генерує. Якщо окремі події не потрібні, використовують `stream()` разом із `finalMessage()` / `get_final_message()`.",
    codexRef: "dev-api-streaming",
  },
  {
    id: "da-3-q11",
    domainId: d,
    levelId: "da-3",
    kind: "scenario",
    difficulty: 2,
    scenario:
      "Користувачі чату скаржаться, що відповідь «зависає» на 8–10 секунд, а потім з'являється вся одразу. Бекенд викликає `messages.create` без streaming і віддає результат фронтенду.",
    prompt: "Що дасть найбільший виграш у сприйнятій швидкості?",
    choices: [
      { id: "a", text: "Збільшити `max_tokens`.", whyWrong: "`max_tokens` — стеля; він не пришвидшує появу першого слова." },
      { id: "b", text: "Кешувати готові відповіді на фронтенді.", whyWrong: "Діалогові відповіді унікальні; кеш готових відповідей майже не спрацює." },
      { id: "c", text: "Показувати спінер довше.", whyWrong: "Це маскує проблему, а не зменшує очікування." },
      { id: "d", text: "Стрімити відповідь і пересилати `text_delta` на фронтенд одразу, як вони приходять." },
    ],
    correct: ["d"],
    explanation:
      "Streaming майже не змінює загальний час генерації, але різко скорочує час до першого токена. Для інтерактивних інтерфейсів це головна метрика сприйнятої швидкості.",
    codexRef: "dev-api-streaming",
  },
  {
    id: "da-3-q12",
    domainId: d,
    levelId: "da-3",
    kind: "single",
    difficulty: 2,
    prompt: "Для чого в подіях `content_block_*` поле `index`?",
    choices: [
      { id: "a", text: "Це порядковий номер події в потоці.", whyWrong: "`index` належить блоку, а не події: усі дельти одного блоку мають однаковий `index`." },
      { id: "b", text: "Це номер спроби після ретраю.", whyWrong: "Ретраї відбуваються на рівні HTTP-запиту й не відображаються в подіях блоків." },
      { id: "c", text: "Він вказує, до якого блоку `content` належить дельта, коли у відповіді кілька блоків (наприклад, `thinking`, `text`, `tool_use`)." },
      { id: "d", text: "Це позиція токена в тексті.", whyWrong: "Позиції токенів у потоці не передаються." },
    ],
    correct: ["c"],
    explanation:
      "Відповідь може містити кілька блоків, і їхні події йдуть з `index`. Збирач потоку тримає буфер на кожен `index` і закриває його на `content_block_stop`.",
    codexRef: "dev-api-streaming",
  },
  {
    id: "da-3-q13",
    domainId: d,
    levelId: "da-3",
    kind: "single",
    difficulty: 3,
    prompt: "Які дельти приходять у блоці `thinking` під час streaming?",
    choices: [
      { id: "a", text: "Лише `text_delta`, як і для звичайного тексту.", whyWrong: "Блок thinking має власний тип дельти, щоб його не сплутали з текстом відповіді." },
      { id: "b", text: "`thinking_delta` з текстом міркувань, а перед закриттям блоку — `signature_delta`." },
      { id: "c", text: "`input_json_delta`, бо thinking — це JSON.", whyWrong: "`input_json_delta` — для аргументів `tool_use`." },
      { id: "d", text: "Жодних: блок thinking приходить повністю в `content_block_start`.", whyWrong: "Thinking стрімиться дельтами так само, як інші блоки." },
    ],
    correct: ["b"],
    explanation:
      "Блок `thinking` отримує `thinking_delta` і підпис `signature_delta`. Підпис потрібен, щоб повернути блок моделі в наступному ході; якщо `display` — `omitted`, текст міркувань порожній.",
    codexRef: "dev-api-streaming",
  },
  {
    id: "da-3-q14",
    domainId: d,
    levelId: "da-3",
    kind: "multi",
    difficulty: 2,
    prompt: "Що НЕ змінюється, коли той самий запит виконують зі streaming?",
    choices: [
      { id: "a", text: "Загальний час до повного завершення генерації суттєво скорочується.", whyWrong: "Streaming скорочує час до першого токена, а не загальний час генерації." },
      { id: "b", text: "Кількість токенів і вартість запиту." },
      { id: "c", text: "Можливості моделі та якість відповіді." },
      { id: "d", text: "Ліміт `max_tokens` перестає діяти.", whyWrong: "`max_tokens` діє однаково в обох режимах." },
      { id: "e", text: "Набір можливих `stop_reason`." },
    ],
    correct: ["b", "c", "e"],
    explanation:
      "Streaming — спосіб доставки, а не інша генерація. Ті самі токени, та сама ціна, ті самі `stop_reason`; змінюється лише те, коли клієнт бачить перші дані.",
    codexRef: "dev-api-streaming",
  },
  {
    id: "da-3-q15",
    domainId: d,
    levelId: "da-3",
    kind: "single",
    difficulty: 2,
    prompt: "Як виглядає одна подія в сирому SSE-потоці Messages API?",
    choices: [
      { id: "a", text: "Рядок `event: <тип>`, рядок `data: <JSON>` і порожній рядок-роздільник." },
      { id: "b", text: "Один JSON-масив усіх подій наприкінці відповіді.", whyWrong: "Тоді це не був би потік: події приходять по одній, щойно готові." },
      { id: "c", text: "Бінарний кадр WebSocket.", whyWrong: "Messages API використовує SSE поверх звичайного HTTP, а не WebSocket." },
      { id: "d", text: "Рядок NDJSON без назви події.", whyWrong: "Кожна подія SSE має рядок `event:` з типом; тип також дублюється в полі `type` у `data`." },
    ],
    correct: ["a"],
    explanation:
      "SSE — текстовий формат: пари `event:`/`data:`, розділені порожнім рядком. Писати свій парсер доводиться рідко — SDK роблять це й повертають типізовані події.",
    codexRef: "dev-api-streaming",
  },
  {
    id: "da-3-q16",
    domainId: d,
    levelId: "da-3",
    kind: "scenario",
    difficulty: 3,
    scenario:
      "Локально streaming працює: текст з'являється по словах. У продакшні за reverse proxy вся відповідь приходить у браузер одним шматком наприкінці. Код однаковий.",
    prompt: "Найімовірніша причина?",
    choices: [
      { id: "a", text: "У продакшні інший API-ключ, який не підтримує streaming.", whyWrong: "Streaming не залежить від ключа; API однаково віддає події." },
      { id: "b", text: "У продакшні модель генерує повільніше.", whyWrong: "Повільніша генерація дала б повільніший потік, а не один шматок наприкінці." },
      { id: "c", text: "SDK вимикає streaming, коли `NODE_ENV=production`.", whyWrong: "SDK не змінює режим залежно від оточення." },
      { id: "d", text: "Проксі буферизує відповідь; для цього маршруту буферизацію треба вимкнути." },
    ],
    correct: ["d"],
    explanation:
      "Проміжні проксі й деякі фреймворки буферизують відповіді цілком. Для SSE-маршрутів буферизацію вимикають, інакше користувач втрачає головну перевагу streaming.",
    codexRef: "dev-api-streaming",
  },
  {
    id: "da-3-q17",
    domainId: d,
    levelId: "da-3",
    kind: "single",
    difficulty: 2,
    prompt: "Чим `client.messages.stream(...)` у Python відрізняється від `client.messages.create(..., stream=True)`?",
    choices: [
      { id: "a", text: "Нічим, це синоніми.", whyWrong: "`create(stream=True)` віддає сирі події без накопичення; хелперів `text_stream` і `get_final_message()` у нього немає." },
      { id: "b", text: "`stream()` не підтримує інструменти.", whyWrong: "Хелпер працює з інструментами й сам збирає `input` блоків `tool_use`." },
      { id: "c", text: "`stream()` накопичує стан повідомлення й дає хелпери (`text_stream`, `get_final_message()`); `create(stream=True)` віддає лише сирі події." },
      { id: "d", text: "`create(stream=True)` не повертає `stop_reason`.", whyWrong: "`stop_reason` приходить у `message_delta` в обох випадках, просто збирати його доводиться самому." },
    ],
    correct: ["c"],
    explanation:
      "`stream()` — високорівневий хелпер, зазвичай у `with`-блоці, що закриває з'єднання. `create(stream=True)` корисний, коли потрібен лише потік сирих подій з мінімальними накладними витратами.",
    codexRef: "dev-api-streaming",
  },
  {
    id: "da-3-q18",
    domainId: d,
    levelId: "da-3",
    kind: "order",
    difficulty: 3,
    prompt: "Розставте кроки обробки виклику інструмента в потоці.",
    choices: [
      { id: "a", text: "`content_block_start` з типом `tool_use`: зберегти `id` і `name`" },
      { id: "b", text: "Накопичувати `partial_json` з `input_json_delta`" },
      { id: "c", text: "На `content_block_stop` розібрати накопичений JSON" },
      { id: "d", text: "Отримати `stop_reason: \"tool_use\"` у `message_delta`" },
      { id: "e", text: "Виконати інструмент і надіслати `tool_result` з тим самим `tool_use_id`" },
    ],
    correct: ["a", "b", "c", "d", "e"],
    explanation:
      "Блок `tool_use` стрімиться як і текст: старт з метаданими, дельти з JSON, стоп. Виконувати інструмент варто після `stop_reason: \"tool_use\"`, коли вся відповідь зібрана.",
    codexRef: "dev-api-streaming",
  },
  {
    id: "da-3-q19",
    domainId: d,
    levelId: "da-3",
    kind: "single",
    difficulty: 3,
    prompt: "Користувач натискає «Зупинити» під час генерації. Як правильно перервати потік у TypeScript SDK?",
    choices: [
      { id: "a", text: "Просто перестати показувати текст, а потік хай дочитається.", whyWrong: "Генерація й з'єднання тривають, витрачаючи токени й ресурси, які вже нікому не потрібні." },
      { id: "b", text: "Викликати `stream.abort()`, щоб закрити з'єднання й припинити генерацію." },
      { id: "c", text: "Надіслати новий запит з `max_tokens: 0`.", whyWrong: "Новий запит не впливає на вже запущений потік." },
      { id: "d", text: "Надіслати в потік подію `message_stop`.", whyWrong: "SSE односпрямований: клієнт не може надсилати події в потік." },
    ],
    correct: ["b"],
    explanation:
      "Зупинка — це закриття з'єднання засобами SDK (`abort()` у TypeScript; у Python — вихід з `with` або `close()`). Частковий текст варто зберегти в історії як незавершений.",
    codexRef: "dev-api-streaming",
  },
  {
    id: "da-3-q20",
    domainId: d,
    levelId: "da-3",
    kind: "scenario",
    difficulty: 2,
    scenario:
      "Нічний job генерує для 5 000 товарів короткі описи по 150 токенів і пише їх у базу. Розробник обробляє кожну подію потоку вручну: дельти, `index`, `message_delta`.",
    prompt: "Що доречніше?",
    choices: [
      { id: "a", text: "Звичайний `messages.create` без streaming: відповіді короткі, UI немає, ручна обробка подій лише ускладнює код." },
      { id: "b", text: "Лишити ручну обробку: streaming обов'язковий для всіх запитів.", whyWrong: "Streaming опційний; він потрібен для UX або довгих генерацій." },
      { id: "c", text: "Писати в базу кожну `text_delta` окремо.", whyWrong: "Тисячі дрібних записів без користі; зберігати варто готовий результат." },
      { id: "d", text: "Запустити всі 5 000 потоків одночасно.", whyWrong: "Це впреться в rate limits незалежно від режиму." },
    ],
    correct: ["a"],
    explanation:
      "Streaming потрібен для інтерактивного UX і довгих виходів. Для коротких фонових задач звичайний запит простіший; для великих офлайн-обсягів варто також розглянути Message Batches.",
    codexRef: "dev-api-streaming",
  },
  // ── da-4: Токени та usage (додатковий пул) ───────────────────────────────
  {
    id: "da-4-q9",
    domainId: d,
    levelId: "da-4",
    kind: "single",
    difficulty: 2,
    prompt: "Куди в `usage` потрапляють токени extended thinking?",
    choices: [
      { id: "a", text: "В `output_tokens`." },
      { id: "b", text: "В `input_tokens`.", whyWrong: "Thinking генерує модель у цьому запиті, тож це вихід." },
      { id: "c", text: "В окреме поле `thinking_tokens`, яке не тарифікується.", whyWrong: "Окремого безкоштовного поля немає; thinking оплачується як вихід." },
      { id: "d", text: "Нікуди, якщо текст міркувань приховано.", whyWrong: "Приховування тексту не скасовує ні генерацію, ні оплату." },
    ],
    correct: ["a"],
    explanation:
      "Thinking — вихідні токени, навіть якщо текст міркувань не показується. Тому `output_tokens` у запиті з thinking може бути значно більшим за видимий текст.",
    codexRef: "dev-api-tokens",
  },
  {
    id: "da-4-q10",
    domainId: d,
    levelId: "da-4",
    kind: "scenario",
    difficulty: 2,
    scenario:
      "Розробник позначив великий системний промпт `cache_control`, але в `usage` щоразу `cache_read_input_tokens: 0`. На початку системного промпта стоїть рядок `Поточний час: {datetime.now()}`.",
    prompt: "Що не так?",
    choices: [
      { id: "a", text: "Кеш працює лише в streaming.", whyWrong: "Кешування не залежить від режиму доставки." },
      { id: "b", text: "Час змінює префікс у кожному запиті, тож кеш ніколи не збігається; динамічні дані треба перенести після точки кешу." },
      { id: "c", text: "`cache_control` не можна ставити на `system`.", whyWrong: "Можна: блок системного промпта — типове місце для точки кешу." },
      { id: "d", text: "Потрібно викликати `count_tokens` перед кожним запитом, щоб прогріти кеш.", whyWrong: "Підрахунок токенів не записує нічого в кеш." },
    ],
    correct: ["b"],
    explanation:
      "Кеш — це точний збіг префікса. Будь-яка змінна частина перед точкою кешу скидає його щоразу; `cache_read_input_tokens` показує, чи кеш реально спрацював.",
    codexRef: "dev-api-tokens",
  },
  {
    id: "da-4-q11",
    domainId: d,
    levelId: "da-4",
    kind: "multi",
    difficulty: 2,
    prompt: "Що варто робити для коректного обліку вартості API?",
    choices: [
      { id: "a", text: "Логувати `usage` з кожної відповіді разом із `model`." },
      { id: "b", text: "Множити кожне поле `usage` на ставку саме цієї моделі й цього типу токенів." },
      { id: "c", text: "Рахувати токени за довжиною рядка відповіді.", whyWrong: "Довжина рядка не дорівнює токенам і ігнорує thinking та кешовані поля." },
      { id: "d", text: "Після кожної відповіді викликати `count_tokens`, бо `usage` неточний.", whyWrong: "`usage` — фактичний облік; `count_tokens` потрібен для оцінки до запиту." },
      { id: "e", text: "Агрегувати витрати за фічею чи клієнтом." },
    ],
    correct: ["a", "b", "e"],
    explanation:
      "Точна вартість — це `usage` × ставки конкретної моделі з урахуванням кешованих полів. Агрегація за фічами показує, де реально йдуть гроші.",
    codexRef: "dev-api-tokens",
  },
  {
    id: "da-4-q12",
    domainId: d,
    levelId: "da-4",
    kind: "single",
    difficulty: 3,
    prompt: "Як ростуть сумарні вхідні токени довгого чату без кешування й обрізання історії?",
    choices: [
      { id: "a", text: "Лінійно: кожен хід додає лише своє повідомлення.", whyWrong: "Кожен хід надсилає всю попередню історію заново, тож лінійно росте розмір одного запиту, а не сума." },
      { id: "b", text: "Не ростуть: API зберігає історію.", whyWrong: "API не має стану; історія щоразу надсилається й тарифікується." },
      { id: "c", text: "Логарифмічно, бо старі повідомлення стискаються автоматично.", whyWrong: "Без явно ввімкненої компакції нічого не стискається автоматично." },
      { id: "d", text: "Приблизно квадратично: N-й запит містить усі попередні ходи." },
    ],
    correct: ["d"],
    explanation:
      "Розмір N-го запиту росте лінійно, тож сума за розмову — приблизно квадратично. Кешування стабільного префікса й стискання історії — основні важелі.",
    codexRef: "dev-api-tokens",
  },
  {
    id: "da-4-q13",
    domainId: d,
    levelId: "da-4",
    kind: "order",
    difficulty: 2,
    prompt: "Розставте кроки захисту від переповнення контексту перед запитом.",
    choices: [
      { id: "a", text: "Порахувати вхідні токени запиту через `count_tokens`" },
      { id: "b", text: "Порівняти з `max_input_tokens` моделі мінус запас під `max_tokens`" },
      { id: "c", text: "Якщо не влазить — стиснути або прибрати старі ходи, зберігши ключові факти" },
      { id: "d", text: "Надіслати запит і звірити фактичний `usage`" },
    ],
    correct: ["a", "b", "c", "d"],
    explanation:
      "Бюджет контексту ділиться між входом і виходом. Перевірка до запиту дешевша за 400 чи обрізану відповідь, а `usage` після запиту підтверджує оцінку.",
    codexRef: "dev-api-tokens",
  },
  {
    id: "da-4-q14",
    domainId: d,
    levelId: "da-4",
    kind: "single",
    difficulty: 2,
    prompt: "Що правда про ендпоінт `count_tokens`?",
    choices: [
      { id: "a", text: "Він тарифікується як звичайний запит до моделі.", whyWrong: "Підрахунок токенів не генерує відповіді й не тарифікується як запит до моделі." },
      { id: "b", text: "Він приймає лише текст `messages`, без `tools` і `system`.", whyWrong: "Він приймає ту саму структуру, що й створення повідомлення, включно з `tools` і `system`." },
      { id: "c", text: "Він безкоштовний, має власні rate limits і повертає `input_tokens` для вказаної моделі." },
      { id: "d", text: "Він повертає і вхідні, і вихідні токени майбутньої відповіді.", whyWrong: "Вихід ще не згенерований, тож його неможливо порахувати заздалегідь." },
    ],
    correct: ["c"],
    explanation:
      "`count_tokens` рахує лише вхід для конкретної моделі. Його можна викликати часто, але з урахуванням власних лімітів запитів.",
    codexRef: "dev-api-tokens",
  },
  {
    id: "da-4-q15",
    domainId: d,
    levelId: "da-4",
    kind: "scenario",
    difficulty: 3,
    scenario:
      "Сервіс показує користувачу `response.content[0].text`. Деякі запити повертають HTTP 200, але екран лишається порожнім. У логах у таких відповідях `stop_reason: \"refusal\"`.",
    prompt: "Як виправити обробку?",
    choices: [
      { id: "a", text: "Повторювати такі запити, доки не прийде текст.", whyWrong: "Відмова — рішення класифікатора щодо цього запиту; повтор без змін зазвичай дає той самий результат." },
      { id: "b", text: "Перевіряти `stop_reason` перед читанням `content` і показувати для `refusal` окреме повідомлення." },
      { id: "c", text: "Вважати це помилкою мережі.", whyWrong: "Відповідь 200 прийшла повністю; мережа тут ні до чого." },
      { id: "d", text: "Збільшити `max_tokens`.", whyWrong: "Обрізання дає `max_tokens`, а тут модель відмовилась відповідати." },
    ],
    correct: ["b"],
    explanation:
      "`refusal` приходить з кодом 200, тож без перевірки `stop_reason` код сприйме його як успіх. Деталі категорії, якщо вони є, лежать у `stop_details`.",
    codexRef: "dev-api-tokens",
  },
  {
    id: "da-4-q16",
    domainId: d,
    levelId: "da-4",
    kind: "single",
    difficulty: 2,
    prompt: "Як зменшити вхідні токени запиту зі скриншотами високої роздільності?",
    choices: [
      { id: "a", text: "Зменшити зображення до розміру, достатнього для задачі, перед кодуванням у base64." },
      { id: "b", text: "Надіслати зображення як текст base64 — так дешевше.", whyWrong: "Base64 як текст — це тисячі текстових токенів і жодного зображення для моделі." },
      { id: "c", text: "Поставити `max_tokens` нижче.", whyWrong: "`max_tokens` обмежує вихід і не впливає на токени зображення." },
      { id: "d", text: "Нічого: зображення не тарифікуються.", whyWrong: "Зображення тарифікуються як вхідні токени, і їхня кількість залежить від розміру." },
    ],
    correct: ["a"],
    explanation:
      "Зображення перетворюються на вхідні токени пропорційно площі. Зменшення до потрібної роздільності заощаджує токени, не шкодячи задачі, якщо деталі лишаються читабельними.",
    codexRef: "dev-api-tokens",
  },
  {
    id: "da-4-q17",
    domainId: d,
    levelId: "da-4",
    kind: "single",
    difficulty: 3,
    prompt: "Розробник ставить `max_tokens: 200`, щоб отримувати короткі відповіді. Що відбувається насправді?",
    choices: [
      { id: "a", text: "Модель планує відповідь так, щоб вкластися в 200 токенів.", whyWrong: "Модель не бачить значення `max_tokens` і не планує довжину під нього." },
      { id: "b", text: "API стискає відповідь до 200 токенів після генерації.", whyWrong: "Нічого не стискається: генерація просто обривається на ліміті." },
      { id: "c", text: "Запит поверне 400, якщо відповідь довша.", whyWrong: "Досягнення ліміту — не помилка, а `stop_reason: \"max_tokens\"`." },
      { id: "d", text: "Довгі відповіді обриваються посеред думки; довжиною треба керувати інструкцією в промпті, а `max_tokens` лишити із запасом." },
    ],
    correct: ["d"],
    explanation:
      "`max_tokens` — запобіжник, про який модель не знає. Бажану довжину задають промптом («до трьох речень»), а ліміт ставлять так, щоб він спрацьовував лише в аварійних випадках.",
    codexRef: "dev-api-tokens",
  },
  {
    id: "da-4-q18",
    domainId: d,
    levelId: "da-4",
    kind: "scenario",
    difficulty: 3,
    scenario:
      "Сервіс відсікає запити, для яких `count_tokens` показує понад 150 000 токенів. Бухгалтерія помітила, що фактичний `usage.input_tokens` інколи трохи відрізняється від оцінки.",
    prompt: "Як до цього ставитись?",
    choices: [
      { id: "a", text: "Це баг SDK, треба рахувати токени самостійно.", whyWrong: "Власний підрахунок буде значно менш точним, ніж ендпоінт." },
      { id: "b", text: "Перестати використовувати `count_tokens`, бо він неточний.", whyWrong: "Невелика похибка не скасовує користі оцінки для захисту від переповнення." },
      { id: "c", text: "Це очікувано: `count_tokens` — оцінка, а рахунок виставляють за `usage`; поріг варто ставити з невеликим запасом." },
      { id: "d", text: "Щоразу надсилати запит двічі й брати менше значення.", whyWrong: "Подвійна вартість заради доступної інформації; облік ведуть за фактичним `usage`." },
    ],
    correct: ["c"],
    explanation:
      "Документація описує результат `count_tokens` як оцінку, що може трохи відрізнятися від фактичного обліку. Для порогів закладають запас, а для рахунків беруть `usage`.",
    codexRef: "dev-api-tokens",
  },
  {
    id: "da-4-q19",
    domainId: d,
    levelId: "da-4",
    kind: "single",
    difficulty: 2,
    prompt: "Після підключення 30 інструментів `input_tokens` кожного запиту зріс на кілька тисяч, хоча повідомлення ті самі. Чому?",
    choices: [
      { id: "a", text: "API стягує фіксовану плату за кожен інструмент.", whyWrong: "Фіксованої плати немає; платять за токени визначень." },
      { id: "b", text: "Назви, описи та схеми інструментів передаються як вхід у кожному запиті." },
      { id: "c", text: "Модель читає код інструментів з вашого сервера.", whyWrong: "Модель бачить лише визначення, надіслані в запиті; до вашого коду доступу немає." },
      { id: "d", text: "Це тимчасово, доки інструменти не закешуються автоматично.", whyWrong: "Автоматично нічого не кешується без `cache_control`; і навіть кешовані токени лишаються у вікні контексту." },
    ],
    correct: ["b"],
    explanation:
      "Визначення інструментів — частина промпта, тож вони займають контекст і коштують у кожному запиті. Зайві інструменти варто прибирати або кешувати стабільний список.",
    codexRef: "dev-api-tokens",
  },
  {
    id: "da-4-q20",
    domainId: d,
    levelId: "da-4",
    kind: "multi",
    difficulty: 3,
    prompt: "Що реально зменшує витрати на вхідні токени в повторюваних запитах?",
    choices: [
      { id: "a", text: "Нижчий `max_tokens`.", whyWrong: "`max_tokens` обмежує лише вихід." },
      { id: "b", text: "Перехід на streaming.", whyWrong: "Streaming не змінює ні кількості токенів, ні ціни." },
      { id: "c", text: "Prompt caching стабільного префікса (інструменти, `system`, спільні документи)." },
      { id: "d", text: "Прибирання непотрібних інструментів і старих ходів історії." },
      { id: "e", text: "Зменшення зображень до потрібної роздільності." },
    ],
    correct: ["c", "d", "e"],
    explanation:
      "Вхід дешевшає або від кешування (дешевше читання того самого префікса), або від того, що токенів просто менше. Параметри виходу й режим доставки на вхід не впливають.",
    codexRef: "dev-api-tokens",
  },
  // ── da-5: Помилки та ретраї (додатковий пул) ─────────────────────────────
  {
    id: "da-5-q9",
    domainId: d,
    levelId: "da-5",
    kind: "single",
    difficulty: 2,
    prompt: "Запит із великим PDF повертає 413 `request_too_large`. Що робити?",
    choices: [
      { id: "a", text: "Повторити з backoff.", whyWrong: "Розмір запиту від повтору не зміниться." },
      { id: "b", text: "Перейти на streaming.", whyWrong: "Streaming стосується відповіді, а не розміру тіла запиту." },
      { id: "c", text: "Збільшити `max_tokens`.", whyWrong: "`max_tokens` про вихід; 413 — про розмір вхідного тіла." },
      { id: "d", text: "Зменшити тіло запиту: розбити документ, стиснути зображення або завантажити файл через Files API й посилатися на `file_id`." },
    ],
    correct: ["d"],
    explanation:
      "413 означає, що тіло запиту перевищує допустимий розмір. Це не тимчасова помилка: зменшують вхід або передають великі файли посиланням.",
    codexRef: "dev-api-errors",
  },
  {
    id: "da-5-q10",
    domainId: d,
    levelId: "da-5",
    kind: "single",
    difficulty: 3,
    prompt: "На що дивитися, щоб знижувати темп запитів ще до отримання 429?",
    choices: [
      { id: "a", text: "На `usage.output_tokens` останньої відповіді.", whyWrong: "`usage` описує один запит і нічого не каже про залишок ліміту." },
      { id: "b", text: "На заголовки відповіді `anthropic-ratelimit-*` із залишком запитів і токенів та часом скидання." },
      { id: "c", text: "На поле `rate_limit` у тілі відповіді.", whyWrong: "Такого поля в тілі немає; ця інформація йде в заголовках." },
      { id: "d", text: "На кількість відкритих TCP-з'єднань.", whyWrong: "Ліміти рахуються в запитах і токенах за хвилину, а не в з'єднаннях." },
    ],
    correct: ["b"],
    explanation:
      "Ліміти рахуються в запитах, вхідних і вихідних токенах за хвилину. Заголовки `anthropic-ratelimit-*` дозволяють плавно гальмувати до того, як сервер почне відповідати 429.",
    codexRef: "dev-api-errors",
  },
  {
    id: "da-5-q11",
    domainId: d,
    levelId: "da-5",
    kind: "scenario",
    difficulty: 3,
    scenario:
      "Сервіс робить не-streaming запити з великим `max_tokens` для довгих звітів. Час від часу користувач чекає втричі довше за налаштований таймаут, а потім однаково отримує помилку таймауту.",
    prompt: "Що відбувається і як виправити?",
    choices: [
      { id: "a", text: "API ігнорує таймаут клієнта.", whyWrong: "Таймаут — налаштування клієнта, і SDK його дотримується для кожної спроби." },
      { id: "b", text: "Мережа нестабільна, треба збільшити `max_retries`.", whyWrong: "Більше повторів лише подовжить очікування: кожен повтор знову впирається в той самий таймаут." },
      { id: "c", text: "SDK повторює запити, що впали по таймауту, тож загальний час доходить до `timeout × (max_retries + 1)`; довгі генерації варто перевести на streaming." },
      { id: "d", text: "Треба зменшити `max_tokens` до 100.", whyWrong: "Це зламає самі звіти, які мають бути довгими." },
    ],
    correct: ["c"],
    explanation:
      "Таймаути SDK вважає тимчасовими й повторює. Для довгих генерацій streaming прибирає проблему в корені, а загальний дедлайн варто рахувати з урахуванням повторів.",
    codexRef: "dev-api-errors",
  },
  {
    id: "da-5-q12",
    domainId: d,
    levelId: "da-5",
    kind: "single",
    difficulty: 3,
    prompt: "Після цього налаштування кожен запит у TypeScript-сервісі падає з таймаутом майже миттєво. Чому?",
    code: { lang: "ts", source: "const client = new Anthropic({ timeout: 60 }); // хотіли 60 секунд" },
    choices: [
      { id: "a", text: "У TypeScript SDK `timeout` задається в мілісекундах; 60 — це 60 мс, а для хвилини треба `60_000`." },
      { id: "b", text: "60 секунд замало для будь-якого запиту.", whyWrong: "Хвилини вистачає для багатьох запитів; тут значення насправді набагато менше за хвилину." },
      { id: "c", text: "Параметр `timeout` у конструкторі ігнорується.", whyWrong: "Він працює, просто в інших одиницях." },
      { id: "d", text: "Таймаут діє лише для streaming.", whyWrong: "Таймаут діє для всіх запитів клієнта." },
    ],
    correct: ["a"],
    explanation:
      "Одиниці таймауту різняться між SDK: у Python — секунди, у TypeScript — мілісекунди. Код, перенесений між мовами, варто перевіряти саме на цьому.",
    codexRef: "dev-api-errors",
  },
  {
    id: "da-5-q13",
    domainId: d,
    levelId: "da-5",
    kind: "single",
    difficulty: 2,
    prompt: "Що логувати, щоб підтримка Anthropic могла знайти конкретний проблемний запит?",
    choices: [
      { id: "a", text: "Повний API-ключ.", whyWrong: "Ключ — секрет; його не логують і не пересилають." },
      { id: "b", text: "Лише час запиту з точністю до секунди.", whyWrong: "За часом серед тисяч запитів організації конкретний знайти важко." },
      { id: "c", text: "Текст повідомлення про помилку.", whyWrong: "Текст однаковий для багатьох запитів і не ідентифікує конкретний." },
      { id: "d", text: "Ідентифікатор запиту із заголовка `request-id` (у SDK — `_request_id` відповіді)." },
    ],
    correct: ["d"],
    explanation:
      "Кожна відповідь має унікальний `request-id`. Його логують поряд з `usage` і `stop_reason`, щоб корелювати власні логи з даними на боці API.",
    codexRef: "dev-api-errors",
  },
  {
    id: "da-5-q14",
    domainId: d,
    levelId: "da-5",
    kind: "multi",
    difficulty: 3,
    prompt: "Агент з інструментами працює з автоматичними повторами. Що треба зробити ідемпотентним, щоб повтор не зашкодив?",
    choices: [
      { id: "a", text: "Сам виклик `messages.create`: він створює стан на сервері, який треба прибрати.", whyWrong: "Генерація не має зовнішніх побічних ефектів; повтор коштує лише токенів." },
      { id: "b", text: "Читання з кешу prompt caching.", whyWrong: "Читання кешу не має побічних ефектів." },
      { id: "c", text: "Інструмент, що списує гроші з клієнта." },
      { id: "d", text: "Інструмент, що надсилає email." },
      { id: "e", text: "Інструмент, що створює запис у базі даних." },
    ],
    correct: ["c", "d", "e"],
    explanation:
      "Небезпечні не повтори API, а повторне виконання ваших дій з побічними ефектами. Для них використовують власні ключі ідемпотентності (наприклад, похідні від `tool_use_id`) і перевірку «вже виконано».",
    codexRef: "dev-api-errors",
  },
  {
    id: "da-5-q15",
    domainId: d,
    levelId: "da-5",
    kind: "scenario",
    difficulty: 2,
    scenario:
      "У пікові години частина запитів отримує 529 навіть після всіх автоматичних повторів SDK. Функція некритична: користувачу потрібна хоч якась відповідь за кілька секунд.",
    prompt: "Що доречно?",
    choices: [
      { id: "a", text: "Повторювати в циклі без пауз, доки не вийде.", whyWrong: "Без пауз ви посилюєте перевантаження й виходите за часовий бюджет." },
      { id: "b", text: "Після вичерпання повторів деградувати: запасна модель, черга на пізніше або зрозуміле повідомлення користувачу." },
      { id: "c", text: "Повертати користувачу сирий текст помилки 529.", whyWrong: "Технічна помилка без пояснення — найгірший UX." },
      { id: "d", text: "Вимкнути повтори, щоб швидше показувати помилку.", whyWrong: "Кілька коротких повторів часто рятують запит; вимикати їх зовсім невигідно." },
    ],
    correct: ["b"],
    explanation:
      "Повтори з backoff — перша лінія, план деградації — друга. Для некритичних функцій запасна модель чи відкладене виконання кращі за довге очікування або сиру помилку.",
    codexRef: "dev-api-errors",
  },
  {
    id: "da-5-q16",
    domainId: d,
    levelId: "da-5",
    kind: "single",
    difficulty: 2,
    prompt: "Як у Python SDK правильно відрізнити rate limit від інших помилок API?",
    choices: [
      { id: "a", text: "`except anthropic.RateLimitError:` — типізований клас винятку." },
      { id: "b", text: "`if \"rate limit\" in str(e):`", whyWrong: "Текст повідомлення може змінитися; порівняння рядків крихке, коли є типізовані класи." },
      { id: "c", text: "`if e.args[0] == 429:`", whyWrong: "Статус лежить в атрибуті `status_code` винятку, а не в `args`; краще ловити конкретний клас." },
      { id: "d", text: "Перевіряти відповідь на `\"error\"` у `response.content`.", whyWrong: "Помилки API піднімаються як винятки; відповіді з `content` при цьому немає." },
    ],
    correct: ["a"],
    explanation:
      "SDK мапить статуси на класи: `BadRequestError`, `AuthenticationError`, `RateLimitError`, `InternalServerError` тощо, з базовим `APIStatusError`. Мережеві збої — окремо: `APIConnectionError` і `APITimeoutError`.",
    codexRef: "dev-api-errors",
  },
  {
    id: "da-5-q17",
    domainId: d,
    levelId: "da-5",
    kind: "single",
    difficulty: 3,
    prompt: "Чому гілка `RateLimitError` у цьому коді ніколи не виконується?",
    code: { lang: "python", source: "try:\n    msg = client.messages.create(**params)\nexcept anthropic.APIStatusError as e:\n    log.error(\"api error %s\", e.status_code)\n    raise\nexcept anthropic.RateLimitError:\n    schedule_retry(params)" },
    choices: [
      { id: "a", text: "`RateLimitError` піднімається лише в асинхронному клієнті.", whyWrong: "Обидва клієнти піднімають ті самі типізовані винятки." },
      { id: "b", text: "SDK ніколи не піднімає 429, бо сам їх повторює.", whyWrong: "Після вичерпання повторів SDK піднімає `RateLimitError`." },
      { id: "c", text: "Потрібно ловити `RateLimitError` у `finally`.", whyWrong: "`finally` не ловить винятків; він виконується завжди." },
      { id: "d", text: "`RateLimitError` — підклас `APIStatusError`, тож перша гілка перехоплює його раніше; специфічні класи треба ловити першими." },
    ],
    correct: ["d"],
    explanation:
      "Python перевіряє `except` згори донизу, і базовий клас перехоплює всі підкласи. Ланцюжок пишуть від найспецифічнішого до найзагальнішого.",
    codexRef: "dev-api-errors",
  },
  {
    id: "da-5-q18",
    domainId: d,
    levelId: "da-5",
    kind: "single",
    difficulty: 2,
    prompt: "Що найчастіше означає 404 `not_found_error` з повідомленням `model: ...`?",
    choices: [
      { id: "a", text: "Тимчасовий збій, варто повторити.", whyWrong: "404 детермінований: повтор з тим самим ідентифікатором дасть той самий результат." },
      { id: "b", text: "Помилка в шляху ендпоінта `/v1/messages`.", whyWrong: "Повідомлення з `model:` вказує саме на модель, а не на шлях." },
      { id: "c", text: "Ідентифікатор моделі з помилкою або модель недоступна вашій організації; перевірте через `GET /v1/models`." },
      { id: "d", text: "Закінчився баланс рахунку.", whyWrong: "Проблеми з оплатою мають власний тип помилки, а не 404 про модель." },
    ],
    correct: ["c"],
    explanation:
      "API однаково відповідає на неіснуючу модель і на модель, недоступну організації. Список доступних моделей повертає Models API.",
    codexRef: "dev-api-errors",
  },
  {
    id: "da-5-q19",
    domainId: d,
    levelId: "da-5",
    kind: "scenario",
    difficulty: 3,
    scenario:
      "Клієнт налаштований з `max_retries=4`. Під час streaming, після кількох сотень токенів, у потоці приходить `overloaded_error`, і код одразу падає з винятком, без жодного повтору.",
    prompt: "Чому автоматичні повтори не спрацювали?",
    choices: [
      { id: "a", text: "`max_retries` не діє для моделей Opus.", whyWrong: "Налаштування повторів не залежить від моделі." },
      { id: "b", text: "Повтори SDK стосуються встановлення запиту; помилка посеред уже розпочатого потоку піднімається у ваш код, і рішення про повтор з частковим виводом ухвалюєте ви." },
      { id: "c", text: "`overloaded_error` ніколи не ретраїться.", whyWrong: "529 до початку відповіді SDK повторює; справа в моменті, коли сталася помилка." },
      { id: "d", text: "Потрібно передати `max_retries` у сам `stream()`.", whyWrong: "Перевизначення для виклику теж стосується лише встановлення запиту." },
    ],
    correct: ["b"],
    explanation:
      "Коли статус 200 уже надіслано й частина тексту показана, автоматичний повтор змінив би вже показаний вивід. Тому обробка помилок посеред потоку — відповідальність застосунку.",
    codexRef: "dev-api-errors",
  },
  {
    id: "da-5-q20",
    domainId: d,
    levelId: "da-5",
    kind: "single",
    difficulty: 2,
    prompt: "Чому погана ідея ставити `max_retries=50` «для надійності»?",
    choices: [
      { id: "a", text: "API блокує клієнтів з понад 10 повторами.", whyWrong: "Такого правила немає; проблема в поведінці самого клієнта." },
      { id: "b", text: "Повтори тарифікуються вдвічі.", whyWrong: "Окремої ставки за повтори немає." },
      { id: "c", text: "SDK не дозволяє більше 5 повторів.", whyWrong: "SDK приймає довільне значення; питання в доцільності." },
      { id: "d", text: "Запит може «висіти» дуже довго, тримати ресурси й посилювати навантаження під час збою; краще кілька повторів і явний план деградації." },
    ],
    correct: ["d"],
    explanation:
      "Із backoff кожен повтор чекає довше, тож десятки спроб означають хвилини очікування. Надійність дають обмежені повтори, дедлайн і запасний шлях, а не нескінченні спроби.",
    codexRef: "dev-api-errors",
  },
  // ── da-boss: БОС: Продакшн-клієнт API (додатковий пул) ───────────────────
  {
    id: "da-boss-q7",
    domainId: d,
    levelId: "da-boss",
    kind: "scenario",
    difficulty: 3,
    scenario:
      "Нічний job обробляє 50 000 документів, запускаючи 200 паралельних запитів. Більшість запитів отримують 429, job триває вдвічі довше, ніж без паралельності. Результати потрібні до ранку, не миттєво.",
    prompt: "Яке рішення найкраще?",
    choices: [
      { id: "a", text: "Збільшити паралельність до 500, щоб швидше пройти хвилю 429.", whyWrong: "Більше паралельних запитів — більше 429; ліміти від цього не зростуть." },
      { id: "b", text: "Прибрати повтори, щоб невдалі документи пропускались.", whyWrong: "Частина документів просто не буде оброблена." },
      { id: "c", text: "Перейти на Message Batches API: асинхронна обробка зі зниженою ціною; або щонайменше обмежити паралельність за заголовками `anthropic-ratelimit-*`." },
      { id: "d", text: "Розподілити запити між кількома ключами однієї організації.", whyWrong: "Ліміти рахуються на рівні організації." },
    ],
    correct: ["c"],
    explanation:
      "Для великих офлайн-обсягів Batches API дешевший і знімає проблему лімітів у реальному часі. Якщо потрібен синхронний API, паралельність узгоджують з лімітами, а не штурмують їх.",
    codexRef: "dev-api-boss",
  },
  {
    id: "da-boss-q8",
    domainId: d,
    levelId: "da-boss",
    kind: "scenario",
    difficulty: 3,
    scenario:
      "Агент викликає інструмент `charge_customer`. Після таймауту мережі між вашим сервером і платіжним провайдером код повторив увесь хід агента, і клієнта списали двічі.",
    prompt: "Що виправити?",
    choices: [
      { id: "a", text: "Вимкнути повтори в SDK.", whyWrong: "Повтор API тут ні до чого: дубль стався у вашому інструменті." },
      { id: "b", text: "Просити модель у промпті не викликати інструмент двічі.", whyWrong: "Повтор ініціював ваш код, а не модель; промпт не дає гарантії." },
      { id: "c", text: "Збільшити таймаут до платіжного провайдера.", whyWrong: "Це зменшить імовірність, але дубль лишиться можливим за наступного збою." },
      { id: "d", text: "Зробити інструмент ідемпотентним: ключ ідемпотентності, похідний від `tool_use_id` чи id замовлення, і перевірка «вже списано» перед дією." },
    ],
    correct: ["d"],
    explanation:
      "Генерацію моделі повторювати безпечно, дії з побічними ефектами — ні. Ідемпотентність реалізують на рівні ваших інструментів, бо саме там реальні наслідки.",
    codexRef: "dev-api-boss",
  },
  {
    id: "da-boss-q9",
    domainId: d,
    levelId: "da-boss",
    kind: "scenario",
    difficulty: 3,
    scenario:
      "Агент на `claude-opus-5-5` з інструментами й thinking. Для компактності логів код зберігає в історії для `assistant` лише `tool_use` блоки, відкидаючи решту. Посеред циклу API почав повертати 400 про невідповідність блоків thinking.",
    prompt: "Як виправити?",
    choices: [
      { id: "a", text: "Вимкнути thinking для цієї моделі.", whyWrong: "На цій моделі thinking не вимикається, а проблема однаково в зміненій історії." },
      { id: "b", text: "Зберігати в історії весь `response.content` без змін, а компактне представлення робити окремо для логів." },
      { id: "c", text: "Генерувати блоки `thinking` з порожнім текстом замість відкинутих.", whyWrong: "Підроблені блоки не пройдуть перевірку підпису." },
      { id: "d", text: "Повторювати запит із backoff.", whyWrong: "400 детермінований; історія лишиться тією самою." },
    ],
    correct: ["b"],
    explanation:
      "Історія для API і лог для людей — різні речі. В API повертають відповідь моделі без змін, особливо блоки `thinking` і `tool_use`; для логів будують окреме представлення.",
    codexRef: "dev-api-boss",
  },
  {
    id: "da-boss-q10",
    domainId: d,
    levelId: "da-boss",
    kind: "multi",
    difficulty: 3,
    prompt: "Сервіс переходить з `claude-haiku-4-5-20251001` на `claude-sonnet-5`. Що треба перевірити в коді клієнта?",
    choices: [
      { id: "a", text: "Змінити ендпоінт на `/v2/messages`.", whyWrong: "Ендпоінт той самий для всіх моделей." },
      { id: "b", text: "Прибрати `temperature`, `top_p` і `top_k`, якщо вони є." },
      { id: "c", text: "Замінити `thinking` з `budget_tokens` на `{type: \"adaptive\"}` з `effort`." },
      { id: "d", text: "Прогнати eval-набір і перерахувати бюджет за фактичним `usage`." },
      { id: "e", text: "Перевести `messages` у новий формат з полем `turns`.", whyWrong: "Формат `messages` не змінюється між моделями." },
    ],
    correct: ["b", "c", "d"],
    explanation:
      "Міграція моделі — це зміна параметрів запиту, які нова модель не приймає, плюс повторне вимірювання якості й вартості. Формат API та ендпоінт лишаються тими самими.",
    codexRef: "dev-api-boss",
  },
  {
    id: "da-boss-q11",
    domainId: d,
    levelId: "da-boss",
    kind: "scenario",
    difficulty: 3,
    scenario:
      "У пікові години потік відповіді інколи зупиняється на пів дорозі, а потім приходить подія `error` з `overloaded_error`. Користувач бачить обірваний текст без пояснень.",
    prompt: "Яка стратегія правильна?",
    choices: [
      { id: "a", text: "Показати користувачу, що відповідь перервалась, і повторити запит з backoff (або дати кнопку «перегенерувати»), не зберігаючи обривок як завершену відповідь." },
      { id: "b", text: "Зберегти частковий текст як нормальну відповідь асистента.", whyWrong: "Незавершена відповідь в історії сплутає і користувача, і модель на наступних ходах." },
      { id: "c", text: "Збільшити `max_retries`: SDK повторить потік автоматично.", whyWrong: "Помилку посеред уже розпочатого потоку SDK піднімає у ваш код." },
      { id: "d", text: "Приховати помилку й чекати, доки потік відновиться сам.", whyWrong: "Після події `error` потік завершено; сам він не відновиться." },
    ],
    correct: ["a"],
    explanation:
      "Помилка посеред потоку — відповідальність застосунку: чесно показати стан, не забруднити історію обривком і повторити з паузою.",
    codexRef: "dev-api-boss",
  },
  {
    id: "da-boss-q12",
    domainId: d,
    levelId: "da-boss",
    kind: "single",
    difficulty: 2,
    prompt: "Інтерактивна функція має SLA на час до першого символу. Що дає найбільший ефект без втрати якості там, де вона не потрібна?",
    choices: [
      { id: "a", text: "Зменшити `max_tokens` до мінімуму.", whyWrong: "Це обріже відповіді, але не пришвидшить появу першого токена." },
      { id: "b", text: "Прибрати системний промпт.", whyWrong: "Втрата інструкцій погіршить якість; для швидкості є кращі важелі." },
      { id: "c", text: "Streaming плюс нижчий `effort` або швидша модель для цього маршруту, підтверджені вимірюванням." },
      { id: "d", text: "Ретраїти кожен запит двічі паралельно й брати швидший.", whyWrong: "Подвоєння вартості й навантаження на ліміти заради незначного виграшу." },
    ],
    correct: ["c"],
    explanation:
      "Час до першого токена скорочують streaming і менше попередньої роботи моделі: нижчий `effort` чи швидша модель. Якість підтверджують eval-ом для конкретного маршруту.",
    codexRef: "dev-api-boss",
  },
  {
    id: "da-boss-q13",
    domainId: d,
    levelId: "da-boss",
    kind: "scenario",
    difficulty: 3,
    scenario:
      "Чат підтримки веде розмови на сотні ходів. Після певної довжини запити почали падати з помилкою про перевищення контексту, а вартість довгих розмов непропорційно висока.",
    prompt: "Яке рішення комплексне?",
    choices: [
      { id: "a", text: "Перейти на модель з більшим вікном і нічого не змінювати.", whyWrong: "Більше вікно лише відсуває межу, а квадратичне зростання вартості лишається." },
      { id: "b", text: "Щоразу надсилати лише останні 5 повідомлень.", whyWrong: "Жорстке обрізання губить ранні ключові факти: номер замовлення, домовленості." },
      { id: "c", text: "Збільшити `max_tokens`, щоб відповідь вміщалась.", whyWrong: "Більший `max_tokens` лише зменшує місце для входу." },
      { id: "d", text: "Стежити за розміром через `usage`/`count_tokens`, стискати старі ходи зі збереженням ключових фактів у структурованому стані, кешувати стабільний префікс." },
    ],
    correct: ["d"],
    explanation:
      "Довгі розмови вимагають керування контекстом: вимірювання, стискання зі збереженням фактів і кешування. Жоден окремий параметр запиту цього не замінює.",
    codexRef: "dev-api-boss",
  },
  {
    id: "da-boss-q14",
    domainId: d,
    levelId: "da-boss",
    kind: "single",
    difficulty: 3,
    prompt: "Користувач скаржиться на дивну відповідь учора о 14:32. Що з логів найшвидше дасть змогу розібратися разом з підтримкою Anthropic?",
    choices: [
      { id: "a", text: "Скриншот від користувача.", whyWrong: "Скриншот не ідентифікує запит у системі API." },
      { id: "b", text: "`request-id` цього запиту разом із моделлю, `stop_reason` і `usage`." },
      { id: "c", text: "Хеш API-ключа.", whyWrong: "Ключ ідентифікує організацію, а не конкретний запит." },
      { id: "d", text: "Повний дамп усіх запитів за день.", whyWrong: "Надлишково й ризиковано для даних користувачів; потрібен один конкретний запит." },
    ],
    correct: ["b"],
    explanation:
      "`request-id` — ключ кореляції між вашими логами й даними API. Разом з моделлю, `stop_reason` і `usage` він відповідає на більшість питань розслідування.",
    codexRef: "dev-api-boss",
  },
  {
    id: "da-boss-q15",
    domainId: d,
    levelId: "da-boss",
    kind: "single",
    difficulty: 3,
    prompt: "Який обробник відповіді найповніший для продакшн-клієнта без інструментів?",
    code: { lang: "python", source: "msg = client.messages.create(**params)\nmatch msg.stop_reason:\n    case \"end_turn\" | \"stop_sequence\": ...\n    case \"max_tokens\": ...\n    case \"refusal\": ...\n    case _: ..." },
    choices: [
      { id: "a", text: "Цей: окремі гілки для нормального завершення, обрізання, відмови й запасна гілка для невідомих значень." },
      { id: "b", text: "Достатньо перевіряти лише `end_turn`, решта — рідкісні випадки.", whyWrong: "`max_tokens` і `refusal` трапляються в реальному трафіку, і без обробки користувач отримає обривок або порожнечу." },
      { id: "c", text: "`stop_reason` варто ігнорувати, достатньо перевірити, що `content` не порожній.", whyWrong: "Обрізана відповідь має непорожній `content`, але вона неповна." },
      { id: "d", text: "Замість `match` треба ловити винятки: SDK піднімає виняток на `max_tokens`.", whyWrong: "`max_tokens` — успішна відповідь 200, винятку немає." },
    ],
    correct: ["a"],
    explanation:
      "`stop_reason` — контракт завершення. Надійний клієнт явно обробляє кожне очікуване значення й має запасну гілку для нових, яких API може додати в майбутньому.",
    codexRef: "dev-api-boss",
  },
];
