import type { QuestionSource } from "@/lib/content/types";

const d = "dev-api" as const;

export const questions: QuestionSource[] = [
  // ── Рівень 1: Messages API ───────────────────────────────────────────────
  {
    id: "da-1-q1",
    domainId: d,
    levelId: "da-1",
    kind: "single",
    difficulty: 1,
    prompt: "Які три параметри обов'язкові в тілі запиту `POST /v1/messages`?",
    choices: [
      { id: "a", text: "`model`, `messages`, `temperature`", whyWrong: "`temperature` необов'язковий, а на найновіших моделях його взагалі прибрали." },
      { id: "b", text: "`model`, `max_tokens`, `messages`" },
      { id: "c", text: "`model`, `system`, `messages`", whyWrong: "`system` необов'язковий: запит без системного промпта цілком коректний." },
      { id: "d", text: "`messages`, `max_tokens`, `stream`", whyWrong: "Без `model` API не знає, яку модель запускати; `stream` лише вмикає потоковий режим і за замовчуванням вимкнений." },
    ],
    correct: ["b"],
    explanation:
      "Мінімальний запит — це модель, стеля вихідних токенів і масив повідомлень. `max_tokens` не має значення за замовчуванням, тож його треба вказувати завжди.",
    codexRef: "dev-api-messages",
  },
  {
    id: "da-1-q2",
    domainId: d,
    levelId: "da-1",
    kind: "single",
    difficulty: 2,
    prompt: "Куди правильно передати системний промпт у Messages API?",
    choices: [
      { id: "a", text: "Першим елементом `messages` з `role: \"system\"`.", whyWrong: "Це формат інших API. У Messages API `messages[0]` має бути `user`, а основний системний промпт передають окремим полем." },
      { id: "b", text: "У заголовку `anthropic-system`.", whyWrong: "Такого заголовка немає; заголовки несуть автентифікацію й версію API, а не вміст промпта." },
      { id: "c", text: "У параметрі верхнього рівня `system` поруч із `messages`." },
      { id: "d", text: "Першим текстом у повідомленні `user` з префіксом `System:`.", whyWrong: "Так інструкція стає частиною репліки користувача і втрачає вагу операторської інструкції." },
    ],
    correct: ["c"],
    explanation:
      "`system` — окремий параметр запиту: рядок або масив текстових блоків. Він задає роль і правила для всієї розмови й не змішується з репліками користувача.",
    codexRef: "dev-api-messages",
  },
  {
    id: "da-1-q3",
    domainId: d,
    levelId: "da-1",
    kind: "scenario",
    difficulty: 2,
    scenario:
      "Чат-бот на Messages API відповідає на перше повідомлення «Мене звати Оля». На друге, «Як мене звати?», він каже, що не знає. Код щоразу надсилає лише останнє повідомлення користувача.",
    prompt: "У чому причина?",
    choices: [
      { id: "a", text: "Модель не запам'ятовує імена з міркувань приватності.", whyWrong: "Жодного такого фільтра немає: якщо ім'я є в надісланій історії, модель його бачить." },
      { id: "b", text: "Потрібно передавати `conversation_id` з першої відповіді.", whyWrong: "У Messages API немає ідентифікатора розмови: сервер не зберігає стан між запитами." },
      { id: "c", text: "Треба увімкнути prompt caching, щоб історія зберігалась на сервері.", whyWrong: "Кеш лише здешевлює повторний префікс, який ви однаково надсилаєте; він не замінює історію." },
      { id: "d", text: "API не має стану: кожен запит має містити всю попередню історію `user`/`assistant`." },
    ],
    correct: ["d"],
    explanation:
      "Messages API stateless: модель бачить лише те, що є в поточному запиті. Історію зберігає і щоразу надсилає ваш код.",
    codexRef: "dev-api-messages",
  },
  {
    id: "da-1-q4",
    domainId: d,
    levelId: "da-1",
    kind: "single",
    difficulty: 2,
    prompt: "TypeScript не компілює `response.content[0].text`. Як правильно отримати текст відповіді?",
    code: { lang: "ts", source: "const response = await client.messages.create({\n  model: \"claude-sonnet-5\",\n  max_tokens: 1024,\n  messages: [{ role: \"user\", content: \"Привіт\" }],\n});\nconsole.log(response.content[0].text); // error" },
    choices: [
      { id: "a", text: "Пройти по `response.content` і взяти блоки, у яких `type === \"text\"`." },
      { id: "b", text: "Використати `response.text` — це скорочення для першого блоку.", whyWrong: "У об'єкта `Message` немає поля `text`; текст лежить лише в блоках `content`." },
      { id: "c", text: "Привести тип: `(response.content[0] as any).text`.", whyWrong: "Каст ховає проблему: першим блоком може бути `thinking` або `tool_use`, і тоді ви отримаєте `undefined`." },
      { id: "d", text: "Викликати `JSON.parse(response.content)`.", whyWrong: "`content` — уже розібраний масив об'єктів, а не JSON-рядок." },
    ],
    correct: ["a"],
    explanation:
      "`content` — масив блоків різних типів (discriminated union). Звуження за `type` і дає типобезпечний доступ до `text`, і захищає від відповіді, де текст не перший.",
    codexRef: "dev-api-messages",
  },
  {
    id: "da-1-q5",
    domainId: d,
    levelId: "da-1",
    kind: "multi",
    difficulty: 2,
    prompt: "Які типи блоків можна передати в `content` повідомлення з роллю `user`?",
    choices: [
      { id: "a", text: "`text_delta`", whyWrong: "Це тип дельти в подіях streaming, а не блок запиту." },
      { id: "b", text: "`image`" },
      { id: "c", text: "`document`" },
      { id: "d", text: "`message_delta`", whyWrong: "Це подія потоку відповіді, її не надсилають у запиті." },
      { id: "e", text: "`tool_result`" },
    ],
    correct: ["b", "c", "e"],
    explanation:
      "Вміст повідомлення користувача складається з блоків `text`, `image`, `document` і `tool_result`. Назви з суфіксом `_delta` належать лише до подій streaming.",
    codexRef: "dev-api-messages",
  },
  {
    id: "da-1-q6",
    domainId: d,
    levelId: "da-1",
    kind: "order",
    difficulty: 2,
    prompt: "Розставте кроки одного ходу багатоходового чату на Messages API.",
    choices: [
      { id: "a", text: "Додати нове повідомлення `user` у локальну історію" },
      { id: "b", text: "Викликати `messages.create` з повною історією" },
      { id: "c", text: "Перевірити `stop_reason` відповіді" },
      { id: "d", text: "Додати `response.content` в історію як повідомлення `assistant`" },
    ],
    correct: ["a", "b", "c", "d"],
    explanation:
      "Ваш код — єдиний власник розмови: дописує репліку, надсилає все, перевіряє, чому модель зупинилась, і зберігає відповідь цілими блоками для наступного ходу.",
    codexRef: "dev-api-messages",
  },
  {
    id: "da-1-q7",
    domainId: d,
    levelId: "da-1",
    kind: "single",
    difficulty: 3,
    prompt: "Чому `response.content[0]` — ненадійний спосіб отримати текст відповіді?",
    choices: [
      { id: "a", text: "Масив `content` завжди містить рівно один блок, але його тип може бути невідомим.", whyWrong: "Блоків може бути кілька: `thinking`, кілька `text`, `tool_use` в одній відповіді." },
      { id: "b", text: "Порядок блоків випадковий і змінюється між запитами.", whyWrong: "Порядок не випадковий: блоки йдуть у тій послідовності, в якій модель їх згенерувала." },
      { id: "c", text: "Першим може бути блок `thinking` або `tool_use`, а тексту може бути кілька блоків." },
      { id: "d", text: "SDK повертає `content` у зворотному порядку.", whyWrong: "SDK нічого не переставляє; порядок блоків той самий, що в сирій відповіді API." },
    ],
    correct: ["c"],
    explanation:
      "Відповідь — впорядкований список блоків різних типів. З thinking першим іде блок `thinking`, у tool use текст може передувати `tool_use`, а з citations текст ділиться на кілька блоків.",
    codexRef: "dev-api-messages",
  },
  {
    id: "da-1-q8",
    domainId: d,
    levelId: "da-1",
    kind: "scenario",
    difficulty: 3,
    scenario:
      "Розробник зберігає історію так: `history.push({ role: \"assistant\", content: textOf(response) })`, де `textOf` склеює лише текстові блоки. Після відповіді з `stop_reason: \"tool_use\"` він додає `tool_result` — і отримує 400.",
    prompt: "Як виправити?",
    choices: [
      { id: "a", text: "Передавати `tool_result` у полі `system`, а не в `messages`.", whyWrong: "`tool_result` — блок повідомлення `user`; у `system` він не має сенсу і не пов'язується з викликом." },
      { id: "b", text: "Додавати в історію весь `response.content` без змін, включно з блоками `tool_use`." },
      { id: "c", text: "Згенерувати власний `tool_use_id` для `tool_result`.", whyWrong: "`tool_use_id` мусить збігатися з `id` блоку `tool_use` з попередньої відповіді; вигаданий id ні на що не посилається." },
      { id: "d", text: "Повторити запит — 400 іноді виникає випадково.", whyWrong: "400 — детермінована помилка формату запиту; повтор того самого тіла дасть ту саму помилку." },
    ],
    correct: ["b"],
    explanation:
      "Кожен `tool_result` посилається на `tool_use` з попереднього ходу `assistant`. Якщо зберегти лише текст, ці блоки зникають, і API відхиляє запит. Те саме стосується блоків `thinking`.",
    codexRef: "dev-api-messages",
  },
  // ── Рівень 2: Моделі та параметри ────────────────────────────────────────
  {
    id: "da-2-q1",
    domainId: d,
    levelId: "da-2",
    kind: "single",
    difficulty: 1,
    prompt: "Що робить параметр `max_tokens`?",
    choices: [
      { id: "a", text: "Задає бажану довжину відповіді, до якої модель прагне.", whyWrong: "Модель не цілиться в це число; це жорстка стеля, а не ціль." },
      { id: "b", text: "Обмежує кількість вхідних токенів запиту.", whyWrong: "Вхід обмежує контекстне вікно моделі, а не `max_tokens`." },
      { id: "c", text: "Задає жорстку стелю кількості токенів, які модель може згенерувати у відповіді." },
      { id: "d", text: "Обмежує суму токенів за всю розмову.", whyWrong: "API не має стану розмови; ліміт діє в межах одного запиту." },
    ],
    correct: ["c"],
    explanation:
      "`max_tokens` — стеля для виходу одного запиту. Якщо її досягнуто, генерація обривається зі `stop_reason: \"max_tokens\"`; стислості треба просити в промпті.",
    codexRef: "dev-api-models-params",
  },
  {
    id: "da-2-q2",
    domainId: d,
    levelId: "da-2",
    kind: "single",
    difficulty: 2,
    prompt: "Навіщо в продакшні вказувати `claude-haiku-4-5-20251001`, а не аліас `claude-haiku-4-5`?",
    choices: [
      { id: "a", text: "Ідентифікатор з датою фіксує конкретний знімок моделі, тож поведінка не зміниться без вашого рішення." },
      { id: "b", text: "Аліаси працюють лише в Console, а не через API.", whyWrong: "Аліаси приймає і API; питання лише в тому, що вони можуть вказувати на новіший знімок." },
      { id: "c", text: "Знімок з датою дешевший за аліас.", whyWrong: "Ціна залежить від моделі, а не від того, як ви її назвали." },
      { id: "d", text: "Аліас ігнорує `max_tokens`.", whyWrong: "Параметри запиту працюють однаково для будь-якої форми ідентифікатора." },
    ],
    correct: ["a"],
    explanation:
      "Аліас зручний для експериментів, але може перейти на новіший знімок. Для відтворюваності й регресійних evals у продакшні фіксують точний ідентифікатор.",
    codexRef: "dev-api-models-params",
  },
  {
    id: "da-2-q3",
    domainId: d,
    levelId: "da-2",
    kind: "scenario",
    difficulty: 2,
    scenario:
      "Потрібно щодня класифікувати близько двох мільйонів коротких звернень у 8 категорій. Відповідь має бути за частки секунди, бюджет обмежений.",
    prompt: "З якої моделі почати?",
    choices: [
      { id: "a", text: "З найпотужнішої моделі Opus: помилки класифікації дорогі.", whyWrong: "Для простої класифікації Opus найдорожчий і найповільніший варіант; брати його варто, лише якщо eval покаже, що дешевші моделі не тягнуть." },
      { id: "b", text: "З Haiku 4.5, перевіривши якість на eval-наборі з реальних звернень." },
      { id: "c", text: "З будь-якої моделі з максимальним effort.", whyWrong: "Максимальний effort збільшує latency і вартість там, де задача цього не потребує." },
      { id: "d", text: "Модель не важлива, важливий лише промпт.", whyWrong: "Модель визначає ціну, швидкість і якість; на такому обсязі різниця величезна." },
    ],
    correct: ["b"],
    explanation:
      "Для масових, простих і чутливих до latency задач починають з найшвидшої дешевої моделі й підтверджують якість eval-ом. Сильнішу модель беруть лише там, де вимірювання показує потребу.",
    codexRef: "dev-api-models-params",
  },
  {
    id: "da-2-q4",
    domainId: d,
    levelId: "da-2",
    kind: "single",
    difficulty: 2,
    prompt: "Запит містить `stop_sequences: [\"</answer>\"]`, і модель дійшла до цього рядка. Що буде у відповіді?",
    choices: [
      { id: "a", text: "`stop_reason: \"end_turn\"`, а `</answer>` в кінці тексту.", whyWrong: "Зупинка на власній послідовності має окремий `stop_reason`, і сам маркер у текст не потрапляє." },
      { id: "b", text: "Помилку 400: `stop_sequences` не можна поєднувати з XML-тегами.", whyWrong: "Стоп-послідовність — довільний рядок, XML-теги тут цілком типовий вибір." },
      { id: "c", text: "Генерація продовжиться, а `</answer>` буде позначено в `usage`.", whyWrong: "Досягнута стоп-послідовність зупиняє генерацію; `usage` містить лише лічильники токенів." },
      { id: "d", text: "`stop_reason: \"stop_sequence\"`, поле `stop_sequence` дорівнює `\"</answer>\"`, а сам маркер у текст не входить." },
    ],
    correct: ["d"],
    explanation:
      "Стоп-послідовності зупиняють генерацію на заданому рядку. Відповідь повідомляє, що зупинка сталась саме так і на якому рядку, тож код може відрізнити її від `end_turn` чи `max_tokens`.",
    codexRef: "dev-api-models-params",
  },
  {
    id: "da-2-q5",
    domainId: d,
    levelId: "da-2",
    kind: "single",
    difficulty: 3,
    prompt: "На моделі, яка підтримує `temperature` (наприклад, Haiku 4.5), розробник ставить `temperature: 0`, щоб тести давали однаковий текст. Що з цього правда?",
    choices: [
      { id: "a", text: "`temperature: 0` гарантує побайтово однакову відповідь на той самий запит.", whyWrong: "Навіть при 0 результат не повністю детермінований; тести на точний збіг тексту будуть крихкими." },
      { id: "b", text: "`temperature: 0` робить вивід передбачуванішим, але не гарантує повної детермінованості; тести краще будувати на перевірці властивостей." },
      { id: "c", text: "Допустимий діапазон — від 0 до 2, тож 0 нічого не змінює.", whyWrong: "Діапазон `temperature` у Claude — від 0 до 1, і 0 суттєво зменшує варіативність." },
      { id: "d", text: "`temperature: 0` вимикає thinking.", whyWrong: "Thinking налаштовується окремим параметром `thinking`, а не температурою." },
    ],
    correct: ["b"],
    explanation:
      "Температура керує випадковістю вибору токенів, але не робить модель детермінованою. Тести LLM-коду перевіряють структуру й властивості відповіді, а не точний рядок.",
    codexRef: "dev-api-models-params",
  },
  {
    id: "da-2-q6",
    domainId: d,
    levelId: "da-2",
    kind: "scenario",
    difficulty: 3,
    scenario:
      "Сервіс перевели з Haiku 4.5 на `claude-sonnet-5`, не змінюючи інших параметрів запиту. Тепер кожен виклик повертає 400. У запиті є `temperature: 0.2` і `top_p: 0.9`.",
    prompt: "Що робити?",
    choices: [
      { id: "a", text: "Поставити `temperature: 1`, бо інші значення не підтримуються.", whyWrong: "На цих моделях параметри семплінгу прибрані повністю: помилку дає сама їх присутність, а не значення." },
      { id: "b", text: "Повторювати запит з backoff: це тимчасове перевантаження.", whyWrong: "400 — помилка формату запиту; перевантаження має коди 529 або 5xx." },
      { id: "c", text: "Прибрати `temperature` і `top_p` із запиту; поведінкою керувати промптом і `effort`." },
      { id: "d", text: "Перейменувати `top_p` на `top_k`.", whyWrong: "`top_k` так само прибраний на найновіших моделях." },
    ],
    correct: ["c"],
    explanation:
      "На найновіших моделях `temperature`, `top_p` і `top_k` більше не приймаються, і запит з ними падає з 400. Міграція моделі — це й перевірка параметрів запиту, а не лише заміна рядка `model`.",
    codexRef: "dev-api-models-params",
  },
  {
    id: "da-2-q7",
    domainId: d,
    levelId: "da-2",
    kind: "single",
    difficulty: 2,
    prompt: "Де задають рівень `effort` для адаптивного thinking?",
    code: { lang: "python", source: "client.messages.create(\n    model=\"claude-opus-5-5\",\n    max_tokens=16000,\n    thinking={\"type\": \"adaptive\"},\n    # де effort?\n    messages=[...],\n)" },
    choices: [
      { id: "a", text: "У `output_config={\"effort\": \"high\"}`." },
      { id: "b", text: "У `thinking={\"type\": \"adaptive\", \"effort\": \"high\"}`.", whyWrong: "`effort` не входить у `thinking`; він живе в `output_config` і впливає на всю відповідь, а не лише на міркування." },
      { id: "c", text: "Параметром верхнього рівня `effort=\"high\"`.", whyWrong: "Верхньорівневого `effort` немає: його вкладають в `output_config`." },
      { id: "d", text: "Через `budget_tokens`, бо effort — це лише його псевдонім.", whyWrong: "`effort` — окремий механізм; `budget_tokens` на найновіших моделях узагалі відхиляється." },
    ],
    correct: ["a"],
    explanation:
      "`thinking: {type: \"adaptive\"}` дозволяє моделі самій вирішувати, скільки думати, а `output_config.effort` (`low`…`max`) задає загальний рівень старанності й витрат токенів.",
    codexRef: "dev-api-models-params",
  },
  {
    id: "da-2-q8",
    domainId: d,
    levelId: "da-2",
    kind: "multi",
    difficulty: 3,
    prompt: "Що зазвичай дає зниження `effort` з `high` до `low` на тій самій моделі?",
    choices: [
      { id: "a", text: "Автоматично перемикає запит на дешевшу модель.", whyWrong: "Модель та сама; effort змінює лише те, скільки роботи вона робить." },
      { id: "b", text: "Менше витрачених токенів і нижчу вартість." },
      { id: "c", text: "Меншу latency відповіді." },
      { id: "d", text: "Менше викликів інструментів і стисліші відповіді." },
      { id: "e", text: "Скасування ліміту `max_tokens`.", whyWrong: "`max_tokens` лишається жорсткою стелею за будь-якого effort." },
    ],
    correct: ["b", "c", "d"],
    explanation:
      "`effort` — важіль «ретельність проти витрат» у межах однієї моделі. Низький рівень підходить для простих чи масових маршрутів; для складного коду та агентних задач — `high` і вище.",
    codexRef: "dev-api-models-params",
  },
  // ── Рівень 3: Streaming ──────────────────────────────────────────────────
  {
    id: "da-3-q1",
    domainId: d,
    levelId: "da-3",
    kind: "single",
    difficulty: 1,
    prompt: "Як увімкнути streaming у сирому HTTP-запиті до Messages API?",
    choices: [
      { id: "a", text: "Викликати окремий ендпоінт `/v1/messages/stream`.", whyWrong: "Окремого ендпоінта немає: streaming вмикається полем у тілі того самого `POST /v1/messages`." },
      { id: "b", text: "Додати заголовок `Accept: text/event-stream` без змін у тілі.", whyWrong: "Режим визначає поле `stream` у тілі; заголовок сам його не вмикає." },
      { id: "c", text: "Передати `max_tokens: -1`.", whyWrong: "Від'ємне значення — некоректний запит; `max_tokens` не пов'язаний зі streaming." },
      { id: "d", text: "Додати в тіло `\"stream\": true`; відповідь прийде як server-sent events." },
    ],
    correct: ["d"],
    explanation:
      "Streaming — той самий запит з `\"stream\": true`. Відповідь приходить потоком SSE-подій, з яких збирається те саме повідомлення, що й без streaming.",
    codexRef: "dev-api-streaming",
  },
  {
    id: "da-3-q2",
    domainId: d,
    levelId: "da-3",
    kind: "order",
    difficulty: 2,
    prompt: "Розставте події потоку для відповіді з одним текстовим блоком.",
    choices: [
      { id: "a", text: "`message_start`" },
      { id: "b", text: "`content_block_start`" },
      { id: "c", text: "`content_block_delta` (один або багато разів)" },
      { id: "d", text: "`content_block_stop`" },
      { id: "e", text: "`message_delta`" },
      { id: "f", text: "`message_stop`" },
    ],
    correct: ["a", "b", "c", "d", "e", "f"],
    explanation:
      "Потік обгортає повідомлення (`message_start` … `message_stop`), усередині — блоки з власними start/delta/stop. `message_delta` наприкінці несе `stop_reason` і фінальний `usage`.",
    codexRef: "dev-api-streaming",
  },
  {
    id: "da-3-q3",
    domainId: d,
    levelId: "da-3",
    kind: "single",
    difficulty: 2,
    prompt: "У якій події потоку з'являється фінальний `stop_reason`?",
    choices: [
      { id: "a", text: "У `message_delta` наприкінці потоку." },
      { id: "b", text: "У `message_start`.", whyWrong: "На початку модель ще не знає, чому зупиниться; там `stop_reason` порожній." },
      { id: "c", text: "У кожній `content_block_delta`.", whyWrong: "Дельти блоків несуть лише фрагменти вмісту." },
      { id: "d", text: "У `content_block_stop`.", whyWrong: "Ця подія лише закриває блок за `index`; причину зупинки повідомлення вона не містить." },
    ],
    correct: ["a"],
    explanation:
      "`message_delta` оновлює поля верхнього рівня повідомлення: `stop_reason`, `stop_sequence` і `usage.output_tokens`. Саме тут код дізнається, чи треба виконувати інструменти або обробляти обрізання.",
    codexRef: "dev-api-streaming",
  },
  {
    id: "da-3-q4",
    domainId: d,
    levelId: "da-3",
    kind: "single",
    difficulty: 2,
    prompt: "Як у сирому потоці знайти черговий фрагмент тексту?",
    code: { lang: "ts", source: "for await (const event of stream) {\n  // ?\n}" },
    choices: [
      { id: "a", text: "`event.type === \"message_delta\"` і `event.delta.text`.", whyWrong: "`message_delta` несе `stop_reason` і `usage`, а не текст." },
      { id: "b", text: "`event.type === \"text\"` і `event.text`.", whyWrong: "У сирому потоці немає події `text`; це назва зручної події хелпера SDK, а не SSE-типу." },
      { id: "c", text: "`event.type === \"content_block_delta\"` і `event.delta.type === \"text_delta\"`, текст у `event.delta.text`." },
      { id: "d", text: "`event.type === \"content_block_start\"` і `event.content_block.text`.", whyWrong: "На старті блоку текст порожній; вміст надходить у дельтах." },
    ],
    correct: ["c"],
    explanation:
      "Текст приходить у `content_block_delta` з `delta.type: \"text_delta\"`. Перевірка типу дельти важлива, бо в тому самому потоці бувають `input_json_delta` і `thinking_delta`.",
    codexRef: "dev-api-streaming",
  },
  {
    id: "da-3-q5",
    domainId: d,
    levelId: "da-3",
    kind: "scenario",
    difficulty: 3,
    scenario:
      "Під час streaming модель викликає інструмент. Код на кожну `input_json_delta` робить `JSON.parse(event.delta.partial_json)` і падає з `SyntaxError`.",
    prompt: "Як правильно?",
    choices: [
      { id: "a", text: "Ловити `SyntaxError` і пропускати фрагменти, що не розбираються.", whyWrong: "Так ви втратите частини аргументів і отримаєте неповний або хибний `input`." },
      { id: "b", text: "Склеювати `partial_json` у рядок для блоку з цим `index` і розбирати його після `content_block_stop`." },
      { id: "c", text: "Вимкнути streaming для запитів з інструментами.", whyWrong: "Streaming з інструментами працює; проблема лише в тому, що фрагмент — не повний JSON." },
      { id: "d", text: "Брати аргументи з `content_block_start`.", whyWrong: "На старті блоку `tool_use` є `id` і `name`, але `input` ще порожній." },
    ],
    correct: ["b"],
    explanation:
      "`partial_json` — шматок рядка JSON, а не самостійний документ. Фрагменти накопичують за `index` блоку й розбирають, коли блок закрито; хелпери SDK роблять це самі.",
    codexRef: "dev-api-streaming",
  },
  {
    id: "da-3-q6",
    domainId: d,
    levelId: "da-3",
    kind: "single",
    difficulty: 2,
    prompt: "Що робити з подіями `ping` у потоці?",
    choices: [
      { id: "a", text: "Вважати їх ознакою помилки й перепідключатися.", whyWrong: "`ping` — нормальна частина потоку, а не сигнал проблеми." },
      { id: "b", text: "Відповідати на них, надсилаючи `pong`.", whyWrong: "SSE — односторонній канал; клієнт нічого не відповідає." },
      { id: "c", text: "Додавати їх до тексту як пробіл.", whyWrong: "Вони не несуть вмісту відповіді." },
      { id: "d", text: "Ігнорувати: це службові події, що тримають з'єднання живим." },
    ],
    correct: ["d"],
    explanation:
      "Потік може містити `ping` у будь-який момент. Надійний обробник ігнорує невідомі й службові типи подій, а не падає на них.",
    codexRef: "dev-api-streaming",
  },
  {
    id: "da-3-q7",
    domainId: d,
    levelId: "da-3",
    kind: "multi",
    difficulty: 3,
    prompt: "Які хелпери SDK реально існують для роботи з потоком?",
    choices: [
      { id: "a", text: "Python: `stream.text_stream` — ітератор лише текстових фрагментів." },
      { id: "b", text: "TypeScript: `await stream.finalMessage()` — зібране повідомлення після завершення потоку." },
      { id: "c", text: "Python: `stream.get_final_message()`." },
      { id: "d", text: "TypeScript: `stream.toPromise()` — обгортка всіх подій у Promise, яку треба писати самому для кожного запиту.", whyWrong: "Такого методу немає, і власні обгортки над `.on()` не потрібні: для цього є `finalMessage()`." },
      { id: "e", text: "Python: `stream.join_deltas()` для склеювання JSON інструментів.", whyWrong: "Такого методу немає; SDK накопичує `input` інструментів сам і віддає їх у фінальному повідомленні." },
    ],
    correct: ["a", "b", "c"],
    explanation:
      "`messages.stream()` у SDK накопичує події у фінальне повідомлення. Можна водночас показувати текст через `text_stream` або `on(\"text\")` і отримати повний `Message` через `get_final_message()` / `finalMessage()`.",
    codexRef: "dev-api-streaming",
  },
  {
    id: "da-3-q8",
    domainId: d,
    levelId: "da-3",
    kind: "scenario",
    difficulty: 3,
    scenario:
      "Потік уже віддав кілька абзаців, коли прийшла подія `error` з `overloaded_error`. HTTP-статус відповіді при цьому був 200.",
    prompt: "Як це обробити?",
    choices: [
      { id: "a", text: "Вважати відповідь успішною, бо статус 200.", whyWrong: "Статус 200 надіслано до початку генерації; помилка посеред потоку означає, що відповідь неповна." },
      { id: "b", text: "Дописати до вже показаного тексту фразу «...» і завершити.", whyWrong: "Користувач отримає обрізану відповідь як завершену, а система не дізнається про збій." },
      { id: "c", text: "Обробити подію як помилку: позначити часткову відповідь як незавершену й повторити запит з backoff або запропонувати перегенерувати." },
      { id: "d", text: "Одразу надіслати той самий запит без паузи.", whyWrong: "Перевантаження вимагає паузи; миттєвий повтор лише додає навантаження." },
    ],
    correct: ["c"],
    explanation:
      "У streaming помилка може прийти подією `error` уже після 200. SDK піднімає її як виняток під час ітерації; код має відрізняти часткову відповідь від завершеної.",
    codexRef: "dev-api-streaming",
  },
  // ── Рівень 4: Токени та usage ────────────────────────────────────────────
  {
    id: "da-4-q1",
    domainId: d,
    levelId: "da-4",
    kind: "single",
    difficulty: 1,
    prompt: "Що показують `usage.input_tokens` і `usage.output_tokens` у відповіді?",
    choices: [
      { id: "a", text: "Ліміти токенів вашої організації на хвилину.", whyWrong: "Ліміти приходять у заголовках `anthropic-ratelimit-*`, а не в `usage`." },
      { id: "b", text: "Фактичну кількість вхідних (без кешованих) і згенерованих токенів цього запиту." },
      { id: "c", text: "Оцінку токенів, зроблену до запиту.", whyWrong: "Оцінку до запиту дає `count_tokens`; `usage` — фактичні числа після генерації." },
      { id: "d", text: "Сумарні токени всієї розмови від першого ходу.", whyWrong: "`usage` описує лише цей запит; накопичувати підсумки — задача вашого коду." },
    ],
    correct: ["b"],
    explanation:
      "`usage` — фактичний облік конкретного запиту, за яким виставляють рахунок. Його варто логувати з кожної відповіді разом із моделлю.",
    codexRef: "dev-api-tokens",
  },
  {
    id: "da-4-q2",
    domainId: d,
    levelId: "da-4",
    kind: "single",
    difficulty: 2,
    prompt: "Як точно порахувати вхідні токени запиту до його відправлення?",
    choices: [
      { id: "a", text: "Поділити кількість символів на 4.", whyWrong: "Грубе правило сильно хибить на коді, не-англійському тексті й розмітці." },
      { id: "b", text: "Використати `tiktoken`.", whyWrong: "Це токенізатор іншого вендора; для Claude він дає неправильні числа." },
      { id: "c", text: "Надіслати запит з `max_tokens: 1` і прочитати `usage`.", whyWrong: "Це платний запит заради оцінки, тоді як для підрахунку є окремий ендпоінт." },
      { id: "d", text: "Викликати `client.messages.count_tokens(...)` (`POST /v1/messages/count_tokens`) з тими самими `model`, `system`, `tools` і `messages`." },
    ],
    correct: ["d"],
    explanation:
      "Ендпоінт підрахунку приймає ту саму структуру, що й `messages.create`, і повертає `input_tokens` для конкретної моделі. Це єдиний надійний спосіб оцінити вхід заздалегідь.",
    codexRef: "dev-api-tokens",
  },
  {
    id: "da-4-q3",
    domainId: d,
    levelId: "da-4",
    kind: "scenario",
    difficulty: 2,
    scenario:
      "Команда оцінила бюджет нової фічі, порахувавши токени для однієї моделі, а в продакшн пустила іншу. Фактичні `input_tokens` для тих самих промптів виявились помітно вищими за оцінку.",
    prompt: "Що найімовірніше пояснює різницю?",
    choices: [
      { id: "a", text: "Різні моделі можуть токенізувати той самий текст по-різному; оцінку треба повторити `count_tokens` для цільової моделі." },
      { id: "b", text: "API додає націнку в токенах за нову модель.", whyWrong: "Ціна за токен відрізняється між моделями, але кількість токенів не «накручується»." },
      { id: "c", text: "Помилка в `usage`, їй не варто довіряти.", whyWrong: "`usage` — фактичний облік, за яким виставляють рахунок." },
      { id: "d", text: "Кількість токенів залежить лише від кількості слів, тож різниця — випадковість.", whyWrong: "Токени — не слова: їхня кількість залежить від токенізатора й типу тексту." },
    ],
    correct: ["a"],
    explanation:
      "Токенізатор може змінюватися між поколіннями моделей, тож той самий текст дає різну кількість токенів. Під час міграції моделі бюджет і ліміти контексту перераховують заново.",
    codexRef: "dev-api-tokens",
  },
  {
    id: "da-4-q4",
    domainId: d,
    levelId: "da-4",
    kind: "single",
    difficulty: 2,
    prompt: "Запит використовує prompt caching. Як отримати повну кількість вхідних токенів?",
    code: { lang: "json", source: "\"usage\": {\n  \"input_tokens\": 120,\n  \"cache_creation_input_tokens\": 0,\n  \"cache_read_input_tokens\": 18000,\n  \"output_tokens\": 410\n}" },
    choices: [
      { id: "a", text: "Це просто `input_tokens`, тобто 120.", whyWrong: "`input_tokens` рахує лише некешовану частину після останньої точки кешу." },
      { id: "b", text: "`input_tokens` + `output_tokens`.", whyWrong: "Вихідні токени не входять у вхід, а кешовані поля тут пропущено." },
      { id: "c", text: "`input_tokens` + `cache_creation_input_tokens` + `cache_read_input_tokens`, тобто 18 120." },
      { id: "d", text: "`cache_read_input_tokens`, бо він найбільший.", whyWrong: "Це лише прочитана з кешу частина; решту входу ви втратите." },
    ],
    correct: ["c"],
    explanation:
      "З кешуванням вхід ділиться на три поля з різною ціною: некешований, записаний у кеш і прочитаний з кешу. Повний розмір контексту — їхня сума.",
    codexRef: "dev-api-tokens",
  },
  {
    id: "da-4-q5",
    domainId: d,
    levelId: "da-4",
    kind: "multi",
    difficulty: 3,
    prompt: "Що займає місце в контекстному вікні моделі під час запиту?",
    choices: [
      { id: "a", text: "Визначення інструментів з `tools`." },
      { id: "b", text: "Системний промпт." },
      { id: "c", text: "Уся історія `messages`, включно з `tool_result`." },
      { id: "d", text: "Заголовки `x-api-key` і `anthropic-version`.", whyWrong: "Заголовки — транспортний рівень; моделі вони не передаються." },
      { id: "e", text: "Токени, які модель генерує у відповіді." },
    ],
    correct: ["a", "b", "c", "e"],
    explanation:
      "Контекст — це все, що бачить і створює модель у межах запиту: інструменти, `system`, історія й вихід. Тому для довгої відповіді під вихід треба лишати місце.",
    codexRef: "dev-api-tokens",
  },
  {
    id: "da-4-q6",
    domainId: d,
    levelId: "da-4",
    kind: "single",
    difficulty: 2,
    prompt: "Що означає `stop_reason: \"end_turn\"`?",
    choices: [
      { id: "a", text: "Модель досягла ліміту `max_tokens`.", whyWrong: "Для цього є окреме значення `max_tokens`." },
      { id: "b", text: "Модель природно завершила відповідь." },
      { id: "c", text: "Модель чекає результату інструмента.", whyWrong: "Це `stop_reason: \"tool_use\"`." },
      { id: "d", text: "Розмова закрита, наступний запит неможливий.", whyWrong: "API не має стану розмови: наступний запит завжди можливий." },
    ],
    correct: ["b"],
    explanation:
      "`stop_reason` пояснює, чому генерація зупинилась: `end_turn`, `max_tokens`, `stop_sequence`, `tool_use`, `pause_turn` чи `refusal`. Код має розгалужуватись саме за ним, а не за текстом.",
    codexRef: "dev-api-tokens",
  },
  {
    id: "da-4-q7",
    domainId: d,
    levelId: "da-4",
    kind: "scenario",
    difficulty: 3,
    scenario:
      "Сервіс генерує JSON-звіти. Іноді `JSON.parse` падає на обірваному рядку. У логах видно, що в таких відповідях `stop_reason: \"max_tokens\"`.",
    prompt: "Яке виправлення правильне?",
    choices: [
      { id: "a", text: "Дописувати відсутні `}` і `]`, доки JSON не розбереться.", whyWrong: "Так ви отримаєте синтаксично валідний, але неповний звіт, і втратите дані мовчки." },
      { id: "b", text: "Ловити помилку парсингу й повторювати той самий запит.", whyWrong: "Той самий `max_tokens` на тому самому вході знову обріже відповідь." },
      { id: "c", text: "Зменшити `max_tokens`, щоб модель писала стисліше.", whyWrong: "Модель не підлаштовує довжину під `max_tokens`; обрізань стане більше." },
      { id: "d", text: "Перевіряти `stop_reason` перед парсингом; за `max_tokens` — збільшити ліміт або зменшити обсяг звіту за запит." },
    ],
    correct: ["d"],
    explanation:
      "`stop_reason: \"max_tokens\"` — сигнал неповної відповіді. Перевірка до парсингу перетворює загадковий `SyntaxError` на явну обробку обрізання.",
    codexRef: "dev-api-tokens",
  },
  {
    id: "da-4-q8",
    domainId: d,
    levelId: "da-4",
    kind: "single",
    difficulty: 3,
    prompt: "Як співвідноситься ціна вихідних і вхідних токенів для моделей Claude?",
    choices: [
      { id: "a", text: "Однакова, рахується лише загальна кількість.", whyWrong: "Вхід і вихід тарифікуються окремо й за різними ставками." },
      { id: "b", text: "Вихідні дешевші, бо їх менше.", whyWrong: "Навпаки: генерація кожного токена дорожча за його читання." },
      { id: "c", text: "Вихідні помітно дорожчі за вхідні, тож багатослівні відповіді й thinking швидко здорожують запит." },
      { id: "d", text: "Вихідні безкоштовні, якщо використано streaming.", whyWrong: "Режим доставки не впливає на ціну токенів." },
    ],
    correct: ["c"],
    explanation:
      "Для поточних моделей ставка за вихідний токен у кілька разів вища за вхідний. Тому стислість відповідей і розумний `effort` суттєво впливають на рахунок.",
    codexRef: "dev-api-tokens",
  },
  // ── Рівень 5: Помилки та ретраї ──────────────────────────────────────────
  {
    id: "da-5-q1",
    domainId: d,
    levelId: "da-5",
    kind: "single",
    difficulty: 1,
    prompt: "API повернув 401 `authentication_error`. Що це означає?",
    choices: [
      { id: "a", text: "Перевищено ліміт запитів, треба зачекати.", whyWrong: "Перевищення лімітів — це 429 `rate_limit_error`." },
      { id: "b", text: "API перевантажене.", whyWrong: "Перевантаження — це 529 `overloaded_error`." },
      { id: "c", text: "Ключ відсутній, невалідний або відкликаний; повтор не допоможе, треба виправити облікові дані." },
      { id: "d", text: "Тіло запиту має неправильний формат.", whyWrong: "Помилка формату — це 400 `invalid_request_error`." },
    ],
    correct: ["c"],
    explanation:
      "401 — проблема автентифікації, а не тимчасовий збій. Такі помилки не ретраять: вони повторюватимуться, доки не виправлено ключ.",
    codexRef: "dev-api-errors",
  },
  {
    id: "da-5-q2",
    domainId: d,
    levelId: "da-5",
    kind: "single",
    difficulty: 2,
    prompt: "Чим 429 відрізняється від 529?",
    choices: [
      { id: "a", text: "429 — ваша організація перевищила свої rate limits; 529 — API тимчасово перевантажене для всіх." },
      { id: "b", text: "Це синоніми для різних регіонів.", whyWrong: "Коди мають різний зміст: один про ваші ліміти, інший про стан сервісу." },
      { id: "c", text: "429 — помилка клієнта, яку не можна ретраяти; 529 — можна.", whyWrong: "Обидва тимчасові й обидва ретраять з паузою." },
      { id: "d", text: "529 означає, що модель не знайдено.", whyWrong: "Модель не знайдено — це 404 `not_found_error`." },
    ],
    correct: ["a"],
    explanation:
      "429 `rate_limit_error` пов'язаний з вашими лімітами й часто має `retry-after`. 529 `overloaded_error` — стан сервісу. Обидва обробляють повтором з backoff, але 429 ще й сигналізує, що варто знизити власний темп.",
    codexRef: "dev-api-errors",
  },
  {
    id: "da-5-q3",
    domainId: d,
    levelId: "da-5",
    kind: "scenario",
    difficulty: 2,
    scenario:
      "Воркер отримує 429 із заголовком `retry-after: 20`. Його власний алгоритм повторює запит через 1, 2 і 4 секунди, і всі три спроби знову отримують 429.",
    prompt: "Що змінити?",
    choices: [
      { id: "a", text: "Прибрати паузи й повторювати одразу.", whyWrong: "Миттєві повтори лише спалюють ліміт і продовжують блокування." },
      { id: "b", text: "Збільшити кількість спроб до 50.", whyWrong: "Більше спроб з тими самими паузами дасть більше 429, а не успіх." },
      { id: "c", text: "Перемкнутися на інший API-ключ тієї самої організації.", whyWrong: "Ліміти діють на рівні організації, тож інший ключ тієї ж організації не допоможе." },
      { id: "d", text: "Чекати не менше, ніж вказує `retry-after`, і лише потім повторювати." },
    ],
    correct: ["d"],
    explanation:
      "`retry-after` — пряма вказівка сервера, коли повтор має сенс. Експоненційний backoff — запасний варіант, коли заголовка немає.",
    codexRef: "dev-api-errors",
  },
  {
    id: "da-5-q4",
    domainId: d,
    levelId: "da-5",
    kind: "multi",
    difficulty: 2,
    prompt: "Які помилки має сенс ретраяти автоматично?",
    choices: [
      { id: "a", text: "400 `invalid_request_error`", whyWrong: "Некоректний запит лишиться некоректним при повторі." },
      { id: "b", text: "429 `rate_limit_error`" },
      { id: "c", text: "529 `overloaded_error`" },
      { id: "d", text: "403 `permission_error`", whyWrong: "Брак прав у ключа чи організації не зникне від повтору; це питання налаштувань доступу." },
      { id: "e", text: "Обрив з'єднання чи таймаут мережі" },
    ],
    correct: ["b", "c", "e"],
    explanation:
      "Ретраять тимчасові збої: ліміти, перевантаження, серверні помилки й мережу. Помилки 4xx через сам запит чи облікові дані (400, 401, 403, 404, 413) виправляють у коді або конфігурації.",
    codexRef: "dev-api-errors",
  },
  {
    id: "da-5-q5",
    domainId: d,
    levelId: "da-5",
    kind: "single",
    difficulty: 2,
    prompt: "Навіщо до експоненційного backoff додають jitter (випадкову складову затримки)?",
    choices: [
      { id: "a", text: "Щоб повтори були швидшими в середньому.", whyWrong: "Jitter не про швидкість; він може як збільшити, так і зменшити окрему паузу." },
      { id: "b", text: "Бо API вимагає випадкову затримку.", whyWrong: "API такого не вимагає; це клієнтська практика." },
      { id: "c", text: "Щоб багато клієнтів, які впали одночасно, не повторювали запити синхронно й не створювали нову хвилю навантаження." },
      { id: "d", text: "Щоб уникнути дублювання `request-id`.", whyWrong: "`request-id` генерує сервер для кожного запиту, jitter на нього не впливає." },
    ],
    correct: ["c"],
    explanation:
      "Без jitter клієнти, що отримали 529 одночасно, повторюють теж одночасно — «thundering herd». Випадкова складова розмазує повтори в часі.",
    codexRef: "dev-api-errors",
  },
  {
    id: "da-5-q6",
    domainId: d,
    levelId: "da-5",
    kind: "single",
    difficulty: 3,
    prompt: "Як збільшити кількість автоматичних повторів у Python SDK?",
    code: { lang: "python", source: "import anthropic\n\nclient = anthropic.Anthropic()  # скільки повторів тут?" },
    choices: [
      { id: "a", text: "`anthropic.Anthropic(max_retries=5)` або для окремого виклику `client.with_options(max_retries=5)`; за замовчуванням SDK робить 2 повтори." },
      { id: "b", text: "SDK не ретраїть сам; потрібно обгорнути кожен виклик у власний цикл.", whyWrong: "SDK має вбудовані повтори з backoff для тимчасових помилок." },
      { id: "c", text: "Передати `retries=5` у `messages.create`.", whyWrong: "Такого параметра в тілі запиту немає; це налаштування клієнта." },
      { id: "d", text: "Встановити змінну `ANTHROPIC_RETRIES=5`.", whyWrong: "SDK не читає таку змінну оточення." },
    ],
    correct: ["a"],
    explanation:
      "SDK автоматично повторює 408, 409, 429, 5xx і мережеві помилки з експоненційним backoff. `max_retries` задають на клієнті або перевизначають для окремого виклику.",
    codexRef: "dev-api-errors",
  },
  {
    id: "da-5-q7",
    domainId: d,
    levelId: "da-5",
    kind: "scenario",
    difficulty: 3,
    scenario:
      "Обгортка повторює будь-який виняток до 5 разів з паузою. Після деплою з помилкою в побудові `messages` сервіс став відповідати з великою затримкою, а рахунок за запити не змінився.",
    prompt: "Що не так з обгорткою?",
    choices: [
      { id: "a", text: "Паузи замалі.", whyWrong: "Жодна пауза не виправить некоректний запит." },
      { id: "b", text: "Вона ретраїть детерміновані 400, які ніколи не пройдуть; ретраяти треба лише тимчасові помилки." },
      { id: "c", text: "Треба ретраяти 10 разів замість 5.", whyWrong: "Більше спроб лише збільшить затримку на гарантовано невдалих запитах." },
      { id: "d", text: "Потрібно ловити лише `Exception`, а не `BaseException`.", whyWrong: "Проблема не в ієрархії винятків, а в тому, що повторюються неповторювані помилки." },
    ],
    correct: ["b"],
    explanation:
      "Класифікація помилок — основа політики повторів. Невдалі 400 не тарифікуються, тому рахунок не змінився, але кожен запит чекав усі 5 спроб перед неминучою помилкою.",
    codexRef: "dev-api-errors",
  },
  {
    id: "da-5-q8",
    domainId: d,
    levelId: "da-5",
    kind: "order",
    difficulty: 2,
    prompt: "Розставте кроки політики повторів для виклику API.",
    choices: [
      { id: "a", text: "Перехопити помилку й визначити її тип або статус" },
      { id: "b", text: "Перевірити, чи вона тимчасова (429, 5xx, 529, мережа)" },
      { id: "c", text: "Обчислити паузу: `retry-after` або експоненційний backoff з jitter" },
      { id: "d", text: "Зачекати й повторити, рахуючи спроби" },
      { id: "e", text: "Після ліміту спроб — повернути помилку або перейти на запасний шлях" },
    ],
    correct: ["a", "b", "c", "d", "e"],
    explanation:
      "Надійна політика: класифікувати, чекати стільки, скільки просить сервер або backoff, обмежувати спроби й мати план на випадок вичерпання.",
    codexRef: "dev-api-errors",
  },
  // ── Бос: БОС: Продакшн-клієнт API ────────────────────────────────────────
  {
    id: "da-boss-q1",
    domainId: d,
    levelId: "da-boss",
    kind: "scenario",
    difficulty: 3,
    scenario:
      "У сервісі власна обгортка над `fetch` до `/v1/messages`: ручний SSE-парсер, повтори на будь-який статус ≥ 400 і розбір помилок за текстом повідомлення. Команда витрачає час на баги в цій обгортці.",
    prompt: "Яке рішення найкраще?",
    choices: [
      { id: "a", text: "Дописати в обгортку повтори ще й для мережевих помилок.", whyWrong: "Це латає одну дірку, лишаючи крихкий парсер, повтори на 400 і розбір тексту помилок." },
      { id: "b", text: "Переписати обгортку на WebSocket для стабільнішого потоку.", whyWrong: "Messages API віддає SSE; WebSocket-ендпоінта для нього немає." },
      { id: "c", text: "Перейти на офіційний SDK: типізовані винятки, вбудовані повтори з backoff лише для тимчасових помилок і хелпери streaming." },
      { id: "d", text: "Відмовитись від streaming, щоб прибрати парсер.", whyWrong: "Це погіршить UX і таймаути на довгих відповідях; проблема не в streaming, а в саморобному клієнті." },
    ],
    correct: ["c"],
    explanation:
      "Офіційний SDK уже вирішує типові задачі продакшн-клієнта: класифікацію помилок, повтори, таймаути, збирання потоку. Власний код варто писати поверх нього, а не замість.",
    codexRef: "dev-api-boss",
  },
  {
    id: "da-boss-q2",
    domainId: d,
    levelId: "da-boss",
    kind: "scenario",
    difficulty: 3,
    scenario:
      "Чат стрімить відповіді. Деякі довгі відповіді обриваються посеред коду, а інтерфейс показує їх як завершені. Бекенд пересилає лише `text_delta` і не дивиться на інші події.",
    prompt: "Що додати?",
    choices: [
      { id: "a", text: "Читати `stop_reason` з `message_delta`; для `max_tokens` позначати відповідь як обрізану й пропонувати продовжити, а ліміт переглянути." },
      { id: "b", text: "Автоматично додавати закриття блоку коду в кінці.", whyWrong: "Це маскує обрізання: код лишиться неповним, а користувач цього не побачить." },
      { id: "c", text: "Перейти на не-streaming режим.", whyWrong: "Обрізання за `max_tokens` не залежить від режиму, а таймаути стануть гіршими." },
      { id: "d", text: "Відкидати відповіді довші за певну кількість символів.", whyWrong: "Довжина в символах не каже, чи відповідь завершена." },
    ],
    correct: ["a"],
    explanation:
      "Потік несе не лише текст, а й метадані завершення. `stop_reason` у `message_delta` — єдиний надійний сигнал, чи відповідь повна.",
    codexRef: "dev-api-boss",
  },
  {
    id: "da-boss-q3",
    domainId: d,
    levelId: "da-boss",
    kind: "scenario",
    difficulty: 3,
    scenario:
      "Дашборд вартості сумує `usage.input_tokens` і `usage.output_tokens` з логів. Після ввімкнення prompt caching дашборд показав, що вхідних токенів поменшало в 10 разів, а рахунок від Anthropic зменшився значно менше.",
    prompt: "Що не так з дашбордом?",
    choices: [
      { id: "a", text: "Рахунок Anthropic запізнюється на місяць.", whyWrong: "Невідповідність пояснюється тим, що саме рахує дашборд." },
      { id: "b", text: "Кешування працює лише на частині моделей.", whyWrong: "Якби кеш не працював, `input_tokens` не впав би в 10 разів." },
      { id: "c", text: "Streaming-запити не повертають `usage`.", whyWrong: "Повертають: у `message_start` і `message_delta`." },
      { id: "d", text: "Він ігнорує `cache_creation_input_tokens` і `cache_read_input_tokens`, які теж тарифікуються за своїми ставками." },
    ],
    correct: ["d"],
    explanation:
      "З кешуванням частина входу переходить з `input_tokens` у кешовані поля: запис у кеш дорожчий за звичайний вхід, читання — дешевше. Облік має враховувати всі три поля за їхніми ставками.",
    codexRef: "dev-api-boss",
  },
  {
    id: "da-boss-q4",
    domainId: d,
    levelId: "da-boss",
    kind: "multi",
    difficulty: 3,
    prompt: "Що входить у мінімальний чекліст продакшн-клієнта Messages API?",
    choices: [
      { id: "a", text: "Фіксований ідентифікатор моделі й явно заданий `effort`, а не покладання на значення за замовчуванням." },
      { id: "b", text: "Логування `request-id`, `usage`, `stop_reason` і моделі для кожного запиту." },
      { id: "c", text: "Повтори для всіх 4xx, щоб нічого не губилось.", whyWrong: "Більшість 4xx детерміновані; їхній повтор лише додає затримку." },
      { id: "d", text: "API-ключ у фронтенд-бандлі, щоб зменшити затримку.", whyWrong: "Ключ у браузері може витягти будь-хто; виклики API роблять лише з бекенду." },
      { id: "e", text: "Обробка кожного `stop_reason`, включно з `max_tokens` і `refusal`." },
    ],
    correct: ["a", "b", "e"],
    explanation:
      "Продакшн-клієнт передбачуваний (фіксовані модель і налаштування), спостережуваний (логи з `request-id` і `usage`) і коректно обробляє всі результати, а не лише щасливий шлях.",
    codexRef: "dev-api-boss",
  },
  {
    id: "da-boss-q5",
    domainId: d,
    levelId: "da-boss",
    kind: "scenario",
    difficulty: 3,
    scenario:
      "Щоб не писати бекенд, фронтенд-команда викликає Messages API прямо з браузера, передаючи API-ключ у заголовку. Ключ лежить у змінній збірки.",
    prompt: "Що робити?",
    choices: [
      { id: "a", text: "Обфускувати ключ у бандлі.", whyWrong: "Ключ однаково потрапляє в мережеві запити браузера, де його видно у DevTools." },
      { id: "b", text: "Перенести виклики на бекенд, який тримає ключ у сховищі секретів, автентифікує користувачів і обмежує їхні запити; ключ, що потрапив у бандл, відкликати." },
      { id: "c", text: "Поставити на ключ низький ліміт витрат і лишити як є.", whyWrong: "Ліміт зменшує шкоду, але ключ однаково публічний, і будь-хто вичерпає ваш бюджет." },
      { id: "d", text: "Щодня генерувати новий ключ.", whyWrong: "Кожен новий ключ так само публічний з моменту деплою." },
    ],
    correct: ["b"],
    explanation:
      "API-ключ — секрет сервера. Бекенд-проксі дає ще й контроль: автентифікацію, ліміти на користувача, логування й валідацію запитів.",
    codexRef: "dev-api-boss",
  },
  {
    id: "da-boss-q6",
    domainId: d,
    levelId: "da-boss",
    kind: "order",
    difficulty: 3,
    prompt: "Розставте кроки обробки одного повідомлення користувача в продакшн-чаті.",
    choices: [
      { id: "a", text: "Додати повідомлення в історію й оцінити розмір через `count_tokens`" },
      { id: "b", text: "За потреби стиснути старі ходи, щоб лишилось місце під вихід" },
      { id: "c", text: "Відкрити потік `messages.stream(...)` і пересилати `text_delta` клієнту" },
      { id: "d", text: "На `message_delta` зафіксувати `stop_reason` і `usage`" },
      { id: "e", text: "Зберегти фінальний `content` в історію й записати лог з `request-id`" },
    ],
    correct: ["a", "b", "c", "d", "e"],
    explanation:
      "Підготовка контексту, потокова доставка, фіксація метаданих завершення й збереження повного вмісту — скелет надійного чат-бекенду.",
    codexRef: "dev-api-boss",
  },
];
