import type { Level } from "@/lib/content/types";

const d = "agentic-architecture" as const;

export const levels: Level[] = [
  {
    id: "aa-1",
    domainId: d,
    index: 1,
    title: "Agent Loop",
    subtitle: "Що робить систему агентною і з чого складається цикл gather → act → verify.",
    boss: false,
    codexRef: "agentic-loop",
    questionIds: ["aa-1-q1", "aa-1-q2", "aa-1-q3", "aa-1-q4", "aa-1-q5", "aa-1-q6"],
  },
  {
    id: "aa-2",
    domainId: d,
    index: 2,
    title: "Декомпозиція задач",
    subtitle: "Планування, розбиття на кроки і межа між workflow та автономним агентом.",
    boss: false,
    codexRef: "task-decomposition",
    questionIds: ["aa-2-q1", "aa-2-q2", "aa-2-q3", "aa-2-q4", "aa-2-q5", "aa-2-q6"],
  },
  {
    id: "aa-3",
    domainId: d,
    index: 3,
    title: "Патерни оркестрації",
    subtitle: "Prompt chaining, routing, паралелізація, orchestrator-workers, evaluator-optimizer.",
    boss: false,
    codexRef: "orchestration-patterns",
    questionIds: ["aa-3-q1", "aa-3-q2", "aa-3-q3", "aa-3-q4", "aa-3-q5", "aa-3-q6"],
  },
  {
    id: "aa-4",
    domainId: d,
    index: 4,
    title: "Subagents та ізоляція контексту",
    subtitle: "Коли віддавати роботу субагенту і як не втратити результат по дорозі.",
    boss: false,
    codexRef: "subagents",
    questionIds: ["aa-4-q1", "aa-4-q2", "aa-4-q3", "aa-4-q4", "aa-4-q5", "aa-4-q6"],
  },
  {
    id: "aa-5",
    domainId: d,
    index: 5,
    title: "Claude Agent SDK",
    subtitle: "Agentic loop із коробки: сесії, дозволи, MCP, hooks у коді.",
    boss: false,
    codexRef: "agent-sdk",
    questionIds: ["aa-5-q1", "aa-5-q2", "aa-5-q3", "aa-5-q4", "aa-5-q5", "aa-5-q6"],
  },
  {
    id: "aa-6",
    domainId: d,
    index: 6,
    title: "Guardrails і human-in-the-loop",
    subtitle: "Дозволи, ліміти, точки підтвердження та зупинка агента, що пішов не туди.",
    boss: false,
    codexRef: "guardrails",
    questionIds: ["aa-6-q1", "aa-6-q2", "aa-6-q3", "aa-6-q4", "aa-6-q5", "aa-6-q6"],
  },
  {
    id: "aa-boss",
    domainId: d,
    index: 7,
    title: "БОС: Продакшн-агент",
    subtitle: "Три сценарії, у яких неправильна відповідь звучить як гарна інженерія.",
    boss: true,
    codexRef: "agentic-production",
    questionIds: ["aa-b-q1", "aa-b-q2", "aa-b-q3", "aa-b-q4"],
  },
];
